Import('env')

# NOTE: order is important (check with empty /usr/local/lib !) => using Default() 

dirs = Split("""
beidcommon
beidcommlib
winscarp
newpkcs11
eidlib
belpicgui
beidservicecrl
""")

dirs += ['Belpic PCSC Service']
if env.has_key('WITHJNI'):
    dirs += ['eidlibjni']
if env.has_key('WITHEIDGUI'):
    # this will propagate wxgtk-2.4-config --cppflags --libs to the environment ('env')
    # but always last to build
    dirs += ['eidviewer']

env.Default(dirs)
env.SConscript(dirs = dirs)

prefix = env['PREFIX']
env.Alias('install', env.Install(prefix + '/share/beid/sdk-samples/cpp', 'eidlib/test/test.cpp'))
env.Alias('install', env.Install(prefix + '/share/beid/sdk-samples/cpp', 'eidlib/test/Makefile'))
env.Alias('install', env.Install(prefix + '/share/beid/sdk-samples/java', 'eidlibjni/eidlib/beidlib.jar'))
env.Alias('install', env.Install(prefix + '/share/beid/sdk-samples/java', 'eidlibjni/BEIDCard.html'))
env.Alias('install', env.Install(prefix + '/share/beid/sdk-samples/java', 'eidlibjni/eidlibTest/README'))
env.Alias('install', env.Install(prefix + '/share/beid/sdk-samples/java/eidlibtest', 'eidlibjni/eidlibTest/src/eidlibtest/Test.java'))
