#!/bin/bash

#get the version numbers
source ./set_eidmw_version.sh

echo $MWVER

#update the links
if test -e /usr/local/lib/libbeidpkcs11.$MWVER2.dylib; then
	unlink /usr/local/lib/libbeidpkcs11.$MWVER2.dylib
fi
ln -fs /usr/local/lib/libbeidpkcs11.$MWVER3.dylib /usr/local/lib/libbeidpkcs11.$MWVER2.dylib

if test -e /usr/local/lib/libbeidpkcs11.$MWVER1.dylib; then
	unlink /usr/local/lib/libbeidpkcs11.$MWVER1.dylib
fi
ln -fs /usr/local/lib/libbeidpkcs11.$MWVER2.dylib /usr/local/lib/libbeidpkcs11.$MWVER1.dylib

if test -e /usr/local/lib/libbeidpkcs11.dylib; then
	unlink /usr/local/lib/libbeidpkcs11.dylib
fi
ln -fs /usr/local/lib/libbeidpkcs11.$MWVER1.dylib /usr/local/lib/libbeidpkcs11.dylib


#on OS X 10.10, make sure securityd auto launches pcscd
if [[ $(sw_vers -productVersion) == *10.10* || $(sw_vers -productVersion) == *10.11* ]]; then
sudo python ./enablesecd.py; fi

#prior to OS X 10.11, try to copy tokend to the /System folder (otherwise, the tokends in this folder get priority)
if [[ $(sw_vers -productVersion) == *10.10* || $(sw_vers -productVersion) == *10.9* || $(sw_vers -productVersion) == *10.8* || $(sw_vers -productVersion) == *10.7* ]]; then
	if test -e /System/Library/Security/tokend/BEID.tokend; then
		sudo rm -r /System/Library/Security/tokend/BEID.tokend
	fi
	sudo cp -r /Library/Security/tokend/BEID.tokend /System/Library/Security/tokend/
fi

#correct the org.opensc.pcscd.autostart name if needed (add .plist)
if test -e /Library/LaunchDaemons/org.opensc.pcscd.autostart; then
 mv /Library/LaunchDaemons/org.opensc.pcscd.autostart /Library/LaunchDaemons/org.opensc.pcscd.autostart.plist;
fi

echo "postinstall succeeded"
