#!/bin/bash

#get the version numbers
source ./set_eidmw_version.sh

echo $MWVER

#update the links
if test -e /usr/local/lib/libbeidpkcs11.$MWVER2.dylib; then
	unlink /usr/local/lib/libbeidpkcs11.$MWVER2.dylib
fi
ln -fs /usr/local/lib/libbeidpkcs11.$MWVER3.dylib /usr/local/lib/libbeidpkcs11.$MWVER2.dylib

if test -e /usr/local/lib/libbeidpkcs11.$MWVER1.dylib; then
	unlink /usr/local/lib/libbeidpkcs11.$MWVER1.dylib
fi
ln -fs /usr/local/lib/libbeidpkcs11.$MWVER2.dylib /usr/local/lib/libbeidpkcs11.$MWVER1.dylib

if test -e /usr/local/lib/libbeidpkcs11.dylib; then
	unlink /usr/local/lib/libbeidpkcs11.dylib
fi
ln -fs /usr/local/lib/libbeidpkcs11.$MWVER1.dylib /usr/local/lib/libbeidpkcs11.dylib

#correct the org.opensc.pcscd.autostart name if needed (add .plist)
if test -e /Library/LaunchDaemons/org.opensc.pcscd.autostart; then
 mv /Library/LaunchDaemons/org.opensc.pcscd.autostart /Library/LaunchDaemons/org.opensc.pcscd.autostart.plist;
fi

echo "postinstall succeeded"
