#!/bin/bash
## Remove parts of the previous middleware if they exist
# only remove sub folders of "/Library/Belgium Identity Card/", as BEIDToken will also install in there
if test -e "/Library/Belgium Identity Card"; then
	rm -rf "/Library/Belgium Identity Card/eID Middleware.app"
	rm -rf "/Library/Belgium Identity Card/Licenses"
fi
if test -e "/Library/BelgiumIdentityCard"; then
	rm -rf "/Library/BelgiumIdentityCard"
fi
