#!/bin/bash
## Remove parts (GUI, Tray applet, pkcs11) of the previous middleware parts if they exist
test -e "/Library/Belgium Identity Card" && rm -rf "/Library/Belgium Identity Card"
#test -e /usr/local/lib/pkcs11/beid-pkcs11.bundle && rm -rf /usr/local/lib/pkcs11/beid-pkcs11.bundle
#test -e /usr/local/lib/beid-pkcs11.bundle && rm -rf /usr/local/lib/beid-pkcs11.bundle

## Create /Library/BelgiumIdentityCard/Licenses if it does not exist yet
mkdir -p /Library/BelgiumIdentityCard/Licenses

## Create /usr/local/lib/share if it does not exist yet
mkdir -p /usr/local/lib/share/beid/certs

## Create /usr/local/lib/pkcs11 if it does not exist yet
#mkdir -p /usr/local/lib/pkcs11
