---
stages:
- docker
- test
- build
- validate

include:
- local: .ci/build-configs.yml
- local: .ci/builds-linux.yml
- local: .ci/builds-windows.yml
- local: .ci/builds-macos.yml
- local: .ci/builds-docker.yml
- template: Security/SAST.gitlab-ci.yml

variables:
  LINUX_BASEDIR: .
  DOCKER_BASEDIR: .
  WINDOWS_BASEDIR: .
  MACOS_BASEDIR: .

#######################################
# Stage "docker": build docker images #
#######################################
suse-build-arm:
  extends: .docker-base-arm
  variables:
   IMAGE_NAME: suse-build
  only:
    changes:
    - .ci/dockerfiles/suse-build/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

suse-build-x86:
  extends: .docker-base-x86
  variables:
   IMAGE_NAME: suse-build
  only:
    changes:
    - .ci/dockerfiles/suse-build/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

suse-build-manifest:
  extends: .docker-base-manifest
  variables:
    IMAGE_NAME: suse-build
  only:
    changes:
      - .ci/dockerfiles/suse-build/**/*
      - .ci/builds-docker.yml
      - .ci/build-configs.yml
  needs:
    - job: suse-build-arm
    - job: suse-build-x86

fed-build-arm:
  extends: .docker-base-arm
  variables:
   IMAGE_NAME: fed-build
  only:
    changes:
    - .ci/dockerfiles/fed-build/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

fed-build-x86:
  extends: .docker-base-x86
  variables:
   IMAGE_NAME: fed-build
  only:
    changes:
    - .ci/dockerfiles/fed-build/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

fed-build-manifest:
  extends: .docker-base-manifest
  variables:
    IMAGE_NAME: fed-build
  only:
    changes:
      - .ci/dockerfiles/fed-build/**/*
      - .ci/builds-docker.yml
      - .ci/build-configs.yml
  needs:
    - job: fed-build-arm
    - job: fed-build-x86

deb-build:
  extends: .docker-base-nm
  variables:
   IMAGE_NAME: deb-build
  only:
    changes:
    - .ci/dockerfiles/deb-build/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

deb-repro:
  extends: .docker-base-nm
  variables:
   IMAGE_NAME: deb-repro
  only:
    changes:
    - .ci/dockerfiles/deb-repro/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

deb-scan-build:
  extends: .docker-base-nm
  variables:
   IMAGE_NAME: deb-scan-build
  only:
    changes:
    - .ci/dockerfiles/deb-scan-build/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

deb-sbuild-arm:
  extends: .docker-base-arm
  variables:
   IMAGE_NAME: deb-sbuild
  only:
    changes:
    - .ci/dockerfiles/deb-sbuild/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

deb-sbuild-x86:
  extends: .docker-base-x86
  variables:
   IMAGE_NAME: deb-sbuild
  only:
    changes:
    - .ci/dockerfiles/deb-sbuild/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

deb-sbuild-manifest:
  extends: .docker-base-manifest
  variables:
    IMAGE_NAME: deb-sbuild
  only:
    changes:
      - .ci/dockerfiles/deb-sbuild/**/*
      - .ci/builds-docker.yml
      - .ci/build-configs.yml
  needs:
    - job: deb-sbuild-arm
    - job: deb-sbuild-x86

gtk4-build:
  extends: .docker-base-nm
  variables:
   IMAGE_NAME: gtk4-build
  only:
    changes:
    - .ci/dockerfiles/gtk4-build/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml
  allow_failure: true

deb-testing:
  extends: .docker-base-nm
  variables:
   IMAGE_NAME: deb-testing
  only:
    changes:
    - .ci/dockerfiles/deb-testing/**/*
    - .ci/builds-docker.yml
    - .ci/build-configs.yml

##########################################################################################################
# Stage "test": run a test battery before doing all the hard work (i.e., try to find any problems ASAP) #
##########################################################################################################
test:distcheck:
  stage: test
  extends: .distcheck

test:robot:linux:
  stage: test
  extends: .robot:linux

test:repro:debian:
  stage: test
  extends: .repro:debian

test:scan-build:
  stage: test
  extends: .scan-build

test:gcc-analyze:
  stage: test
  extends: .gcc-analyzer

test:gtk4:
  stage: test
  extends: .gtk4

test:nogtk:
  stage: test
  extends: .nogtk

test:nodialogs:
  stage: test
  extends: .nodialogs

test:coverity:linux:
  stage: test
  extends: .coverity:linux

##############################################################################################################
# Stage "build": build Linux packages (in a child pipeline, without waiting), and Windows and macOS binaries #
##############################################################################################################

# Windows
build:windows:
  stage: build
  extends: .build-windows
  needs:
    - test:distcheck
    - test:robot:linux

# macOS
build:macos:
  stage: build
  extends: .build-macos
  variables:
    EIDMW_SIGN_BUILD: 0
  needs:
    - test:distcheck
    - test:robot:linux

# Linux
build:linux:
  stage: build
  trigger:
    include:
      - local: .ci/package-builds.yml
  variables:
    PARENT_PIPELINE: $CI_PIPELINE_ID

validate:robot:windows:
  stage: validate
  extends: .robot:windows
  needs:
    - job: build:windows
      artifacts: true

validate:robot:macos:
  stage: validate
  extends: .robot:macos
  dependencies:
  - build:macos

#validate:validation:windows:dllinstall:
#  stage: validate
#  extends: .validation:windows:dllinstall
#  dependencies:
#  - build:windows
#  allow_failure: true

#validate:validation:windows:google:
#  stage: validate
#  extends: .validation:windows:google
#  dependencies:
#  - build:windows
#  allow_failure: true

#validate:validation:windows:firefox:
#  stage: validate
#  extends: .validation:windows:firefox
#  dependencies:
#  - build:windows
#  allow_failure: true

#validate:validation:windows:edge:
#  stage: validate
#  extends: .validation:windows:edge
#  dependencies:
#  - build:windows
#  allow_failure: true

#validate:validation:windows:ie:
#  stage: validate
#  extends: .validation:windows:ie
#  dependencies:
#  - build:windows
#  allow_failure: true

validate:validation:linux:google:
  stage: validate
  extends: .validation:linux:google
  allow_failure: true

validate:validation:linux:firefox:
  stage: validate
  extends: .validation:linux:firefox
  allow_failure: true

#Validate:validation:macos:safari:
#  stage: validate
#  extends: .validation:macos:safari
#  dependencies:
#  - build:macos
#  allow_failure: true

validate:validation:macos:google:
  stage: validate
  extends: .validation:macos:google
  dependencies:
  - build:macos
  allow_failure: true

validate:reports:translation-status:
  stage: validate
  extends: .check-translations
