Import('env')
myenv=env.Copy()
myenv.Append(CPPPATH=['../..', '../include', '/usr/include/PCSC'])
myenv.Append(CCFLAGS=' -DHAVE_CONFIG_H')
# LIBPATH before LIBS !?
myenv.Append(LIBPATH='../../../winscarp')
myenv.Append(LIBS=['beidpcsclite', 'crypto', 'ssl'])
obj=myenv.genobj('shlib', myenv)
obj.src=Split("""
asn1.c
ctx.c
log.c
pkcs15-cache.c
pkcs15-pubkey.c
base64.c
dir.c
module.c
pkcs15-cert.c
pkcs15-sec.c
reader-pcsc.c
card-belpic.c
emv.c
padding.c
pkcs15-data.c
pkcs15-wrap.c
sec.c
card.c
errors.c
pkcs15-algo.c
pkcs15-pin.c
portability.c
sc.c
ctbcs.c
iso7816.c
pkcs15.c
pkcs15-prkey.c
../scdl/scdl.c
../scconf/scconf.c
../scconf/write.c
../scconf/parse.c
../scconf/lex-parse.c
""")
obj.target='libbeidlibopensc'
obj.vnum='2.2.0'
obj.execute()
prefix = env['PREFIX']
libdir = env['LIBDIR']
env.Alias('install', env.Install(libdir, obj.target + '.so.' + obj.vnum))
env.Alias('install', env.Install(libdir, obj.target + '.so'))
