#!/bin/bash

echo "postinstall BEIDTokenApp started"

#start the BEIDTokenApp so that the BEID ctkToken gets registered
open "/Library/Belgium Identity Card/BEIDTokenApp.app"

echo "postinstall BEIDTokenApp succeeded"
