#!/bin/bash
# Remove previous version of the BEIDTokenApp.App if it exists
if test -e "/Library/Belgium Identity Card/BEIDTokenApp.App"; then
	rm -rf "/Library/Belgium Identity Card/BEIDTokenApp.App"
fi

