# CMake generated Testfile for 
# Source directory: /Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests
# Build directory: /Users/andyvand/Downloads/eid-mw/libressl/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(aeadtest "aeadtest" "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/aeadtests.txt")
set_tests_properties(aeadtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;19;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(aes_wrap "aes_wrap")
set_tests_properties(aes_wrap PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;24;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(arc4randomforktest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/arc4randomforktest.sh")
set_tests_properties(arc4randomforktest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;31;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(asn1evp "asn1evp")
set_tests_properties(asn1evp PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;37;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(asn1test "asn1test")
set_tests_properties(asn1test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;42;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(asn1time "asn1time")
set_tests_properties(asn1time PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;47;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(base64test "base64test")
set_tests_properties(base64test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;52;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(bftest "bftest")
set_tests_properties(bftest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;57;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(bnaddsub "bnaddsub")
set_tests_properties(bnaddsub PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;70;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(bn_rand_interval "bn_rand_interval")
set_tests_properties(bn_rand_interval PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;76;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(bntest "bntest")
set_tests_properties(bntest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;85;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(bn_to_string "bn_to_string")
set_tests_properties(bn_to_string PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;92;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(buffertest "buffertest")
set_tests_properties(buffertest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;99;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(bytestringtest "bytestringtest")
set_tests_properties(bytestringtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;106;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(casttest "casttest")
set_tests_properties(casttest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;112;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(chachatest "chachatest")
set_tests_properties(chachatest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;117;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(cipher_list "cipher_list")
set_tests_properties(cipher_list PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;123;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(cipherstest "cipherstest")
set_tests_properties(cipherstest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;129;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(cmstest "cmstest")
set_tests_properties(cmstest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;140;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(configtest "configtest")
set_tests_properties(configtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;145;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(cts128test "cts128test")
set_tests_properties(cts128test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;150;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(destest "destest")
set_tests_properties(destest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;155;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(dhtest "dhtest")
set_tests_properties(dhtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;160;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(dsatest "dsatest")
set_tests_properties(dsatest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;165;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(ecdhtest "ecdhtest")
set_tests_properties(ecdhtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;170;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(ecdsatest "ecdsatest")
set_tests_properties(ecdsatest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;175;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(ectest "ectest")
set_tests_properties(ectest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;180;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(enginetest "enginetest")
set_tests_properties(enginetest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;185;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(evptest "evptest" "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/evptests.txt")
set_tests_properties(evptest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;190;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(explicit_bzero "explicit_bzero")
set_tests_properties(explicit_bzero PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;201;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(exptest "exptest")
set_tests_properties(exptest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;210;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(freenull "freenull")
set_tests_properties(freenull PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;216;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(gcm128test "gcm128test")
set_tests_properties(gcm128test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;221;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(gost2814789t "gost2814789t")
set_tests_properties(gost2814789t PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;226;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(hkdf_test "hkdf_test")
set_tests_properties(hkdf_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;231;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(hmactest "hmactest")
set_tests_properties(hmactest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;236;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(ideatest "ideatest")
set_tests_properties(ideatest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;241;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(igetest "igetest")
set_tests_properties(igetest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;246;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(key_schedule "key_schedule")
set_tests_properties(key_schedule PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;252;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(keypairtest "keypairtest" "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/ca.pem" "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/server.pem" "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/server.pem")
set_tests_properties(keypairtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;256;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(md4test "md4test")
set_tests_properties(md4test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;265;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(md5test "md5test")
set_tests_properties(md5test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;270;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(mont "mont")
set_tests_properties(mont PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;275;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(optionstest "optionstest")
set_tests_properties(optionstest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;291;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(pbkdf2 "pbkdf2")
set_tests_properties(pbkdf2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;296;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(pkcs7test "pkcs7test")
set_tests_properties(pkcs7test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;310;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(poly1305test "poly1305test")
set_tests_properties(poly1305test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;315;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pq_test "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/pq_test.sh")
  set_tests_properties(pq_test PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;322;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pq_test "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/pq_test.sh")
  set_tests_properties(pq_test PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;322;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pq_test "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/pq_test.sh")
  set_tests_properties(pq_test PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;322;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pq_test "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/pq_test.sh")
  set_tests_properties(pq_test PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;322;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
else()
  add_test(pq_test NOT_AVAILABLE)
endif()
add_test(randtest "randtest")
set_tests_properties(randtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;336;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(rc2test "rc2test")
set_tests_properties(rc2test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;341;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(rc4test "rc4test")
set_tests_properties(rc4test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;346;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(recordtest "recordtest")
set_tests_properties(recordtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;352;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(rfc5280time "rfc5280time")
set_tests_properties(rfc5280time PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;361;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(rmdtest "rmdtest")
set_tests_properties(rmdtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;367;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(rsa_test "rsa_test")
set_tests_properties(rsa_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;372;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(servertest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/servertest.sh")
  set_tests_properties(servertest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;378;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(servertest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/servertest.sh")
  set_tests_properties(servertest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;378;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(servertest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/servertest.sh")
  set_tests_properties(servertest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;378;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(servertest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/servertest.sh")
  set_tests_properties(servertest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;378;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
else()
  add_test(servertest NOT_AVAILABLE)
endif()
add_test(sha1test "sha1test")
set_tests_properties(sha1test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;387;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(sha256test "sha256test")
set_tests_properties(sha256test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;392;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(sha512test "sha512test")
set_tests_properties(sha512test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;397;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(sm3test "sm3test")
set_tests_properties(sm3test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;402;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(sm4test "sm4test")
set_tests_properties(sm4test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;407;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(ssl_versions "ssl_versions")
set_tests_properties(ssl_versions PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;413;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ssltest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/ssltest.sh")
  set_tests_properties(ssltest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;420;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ssltest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/ssltest.sh")
  set_tests_properties(ssltest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;420;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ssltest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/ssltest.sh")
  set_tests_properties(ssltest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;420;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ssltest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/ssltest.sh")
  set_tests_properties(ssltest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;420;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
else()
  add_test(ssltest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testdsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testdsa.sh")
  set_tests_properties(testdsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;428;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testdsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testdsa.sh")
  set_tests_properties(testdsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;428;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testdsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testdsa.sh")
  set_tests_properties(testdsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;428;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testdsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testdsa.sh")
  set_tests_properties(testdsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;428;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
else()
  add_test(testdsa NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testenc "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testenc.sh")
  set_tests_properties(testenc PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;436;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testenc "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testenc.sh")
  set_tests_properties(testenc PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;436;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testenc "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testenc.sh")
  set_tests_properties(testenc PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;436;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testenc "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testenc.sh")
  set_tests_properties(testenc PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;436;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
else()
  add_test(testenc NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testrsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testrsa.sh")
  set_tests_properties(testrsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;444;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testrsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testrsa.sh")
  set_tests_properties(testrsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;444;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testrsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testrsa.sh")
  set_tests_properties(testrsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;444;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testrsa "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/testrsa.sh")
  set_tests_properties(testrsa PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;444;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
else()
  add_test(testrsa NOT_AVAILABLE)
endif()
add_test(timingsafe "timingsafe")
set_tests_properties(timingsafe PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;453;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(tlsexttest "tlsexttest")
set_tests_properties(tlsexttest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;459;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(tlstest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/tlstest.sh")
  set_tests_properties(tlstest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;474;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(tlstest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/tlstest.sh")
  set_tests_properties(tlstest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;474;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(tlstest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/tlstest.sh")
  set_tests_properties(tlstest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;474;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(tlstest "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/tlstest.sh")
  set_tests_properties(tlstest PROPERTIES  ENVIRONMENT "srcdir=/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests" _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;474;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
else()
  add_test(tlstest NOT_AVAILABLE)
endif()
add_test(tls_ext_alpn "tls_ext_alpn")
set_tests_properties(tls_ext_alpn PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;484;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(tls_prf "tls_prf")
set_tests_properties(tls_prf PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;491;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(utf8test "utf8test")
set_tests_properties(utf8test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;498;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(valid_handshakes_terminate "valid_handshakes_terminate")
set_tests_properties(valid_handshakes_terminate PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;505;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(verifytest "verifytest")
set_tests_properties(verifytest PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;512;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(x25519test "x25519test")
set_tests_properties(x25519test PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;518;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
add_test(x509name "x509name")
set_tests_properties(x509name PROPERTIES  _BACKTRACE_TRIPLES "/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;523;add_test;/Users/andyvand/Downloads/eid-mw/libressl-3.1.0-apple/tests/CMakeLists.txt;0;")
