/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Exception class Bad Transaction (error code = EIDMW_ERR_BAD_TRANSACTION).
/// Throw when a class/function is not used correctly.
/// Used in : 
/// - BEID_ReaderContext::Lock()
/// - BEID_ReaderContext::Unlock()
/// </summary>
public class BEID_ExBadTransaction : BEID_Exception {
  private HandleRef swigCPtr;

  internal BEID_ExBadTransaction(IntPtr cPtr, bool cMemoryOwn) : base(beidlib_dotNetPINVOKE.BEID_ExBadTransactionUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BEID_ExBadTransaction obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BEID_ExBadTransaction() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        beidlib_dotNetPINVOKE.delete_BEID_ExBadTransaction(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BEID_ExBadTransaction() : this(beidlib_dotNetPINVOKE.new_BEID_ExBadTransaction(), true) {
  }

}

}
