/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Class for the id document on a SIS Card.
/// You can get such an object from BEID_SISCard::getID()	(or getDocument).
/// </summary>
public class BEID_SisId : BEID_XMLDoc {
  private HandleRef swigCPtr;

  internal BEID_SisId(IntPtr cPtr, bool cMemoryOwn) : base(beidlib_dotNetPINVOKE.BEID_SisIdUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BEID_SisId obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BEID_SisId() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        beidlib_dotNetPINVOKE.delete_BEID_SisId(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>Return Name field.</summary>
  public string getName()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getName(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Surname field.</summary>
  public string getSurname()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getSurname(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Initials field.</summary>
  public string getInitials()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getInitials(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Gender field.</summary>
  public string getGender()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getGender(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Date Of Birth field.</summary>
  public string getDateOfBirth()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getDateOfBirth(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Social Security Number field.</summary>
  public string getSocialSecurityNumber()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getSocialSecurityNumber(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Logical Number field.</summary>
  public string getLogicalNumber()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getLogicalNumber(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Date Of Issue field.</summary>
  public string getDateOfIssue()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getDateOfIssue(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Validity Begin Date field.</summary>
  public string getValidityBeginDate()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getValidityBeginDate(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return Validity End Date field.</summary>
  public string getValidityEndDate()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_SisId_getValidityEndDate(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
