/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

public enum BEID_RawDataType {
  BEID_RAWDATA_ID = 0,
  BEID_RAWDATA_ID_SIG,
  BEID_RAWDATA_ADDR,
  BEID_RAWDATA_ADDR_SIG,
  BEID_RAWDATA_PICTURE,
  BEID_RAWDATA_CARD_INFO,
  BEID_RAWDATA_TOKEN_INFO,
  BEID_RAWDATA_CERT_RRN,
  BEID_RAWDATA_CHALLENGE,
  BEID_RAWDATA_RESPONSE
}

}
