/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

public enum BEID_DocumentType {

    /// <summary>Full document : usefull for XML/CSV/TLV export</summary>
    BEID_DOCTYPE_FULL = 0,
    
    /// <summary>ID document : usefull to get value by field</summary>
    BEID_DOCTYPE_ID,

    /// <summary>picture document (if available)</summary>
    BEID_DOCTYPE_PICTURE,

    /// <summary>info on the card (if available)</summary>
    BEID_DOCTYPE_INFO,
    
    /// <summary>pins containert (if available)</summary>
    BEID_DOCTYPE_PINS,

    /// <summary>certificates containert (if available)</summary>
    BEID_DOCTYPE_CERTIFICATES
}

}
