/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Exception class Document Type Unknown (error code = EIDMW_ERR_DOCTYPE_UNKNOWN).
/// Throw when the document type doesn't exist for this card.
/// Used in : 
/// - BEID_Card::getDocument(BEID_DocumentType type) 
/// </summary>
public class BEID_ExDocTypeUnknown : BEID_Exception {
  private HandleRef swigCPtr;

  internal BEID_ExDocTypeUnknown(IntPtr cPtr, bool cMemoryOwn) : base(beidlib_dotNetPINVOKE.BEID_ExDocTypeUnknownUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BEID_ExDocTypeUnknown obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BEID_ExDocTypeUnknown() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        beidlib_dotNetPINVOKE.delete_BEID_ExDocTypeUnknown(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BEID_ExDocTypeUnknown() : this(beidlib_dotNetPINVOKE.new_BEID_ExDocTypeUnknown(), true) {
  }

}

}
