/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Exception class File Type Unknown (error code = EIDMW_ERR_FILETYPE_UNKNOWN).
/// Throw when the Raw Data type doesn't exist for this card.
/// Used in : 
/// - BEID_Card::getRawData(BEID_RawDataType type)
/// </summary>
public class BEID_ExFileTypeUnknown : BEID_Exception {
  private HandleRef swigCPtr;

  internal BEID_ExFileTypeUnknown(IntPtr cPtr, bool cMemoryOwn) : base(beidlib_dotNetPINVOKE.BEID_ExFileTypeUnknownUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BEID_ExFileTypeUnknown obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BEID_ExFileTypeUnknown() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        beidlib_dotNetPINVOKE.delete_BEID_ExFileTypeUnknown(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BEID_ExFileTypeUnknown() : this(beidlib_dotNetPINVOKE.new_BEID_ExFileTypeUnknown(), true) {
  }

}

}
