/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Exception class No Card Present (error code = EIDMW_ERR_NO_CARD).
/// Throw when no card is present.
/// Used in : 
/// - BEID_ReaderContext::getCardType() 
/// - BEID_ReaderContext::getCard() 
/// - BEID_ReaderContext::getEIDCard() 
/// - BEID_ReaderContext::getKidsCard() 
/// - BEID_ReaderContext::getForeignerCard()
/// - BEID_ReaderContext::getSISCard()
/// </summary>
public class BEID_ExNoCardPresent : BEID_Exception {
  private HandleRef swigCPtr;

  internal BEID_ExNoCardPresent(IntPtr cPtr, bool cMemoryOwn) : base(beidlib_dotNetPINVOKE.BEID_ExNoCardPresentUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BEID_ExNoCardPresent obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BEID_ExNoCardPresent() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        beidlib_dotNetPINVOKE.delete_BEID_ExNoCardPresent(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BEID_ExNoCardPresent() : this(beidlib_dotNetPINVOKE.new_BEID_ExNoCardPresent(), true) {
  }

}

}
