/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

using System;
using System.Runtime.InteropServices;

public class beidlib_dotNet {
  /// <summary>Function for Logging.</summary>
  public static void BEID_LOG(BEID_LogLevel level, string module_name, string format) {
    beidlib_dotNetPINVOKE.BEID_LOG((int)level, module_name, format);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public static readonly int EIDMW_OK = beidlib_dotNetPINVOKE.EIDMW_OK_get();
  public static readonly int EIDMW_ERR_PARAM_BAD = beidlib_dotNetPINVOKE.EIDMW_ERR_PARAM_BAD_get();
  public static readonly int EIDMW_ERR_PARAM_RANGE = beidlib_dotNetPINVOKE.EIDMW_ERR_PARAM_RANGE_get();
  public static readonly int EIDMW_ERR_BAD_PATH = beidlib_dotNetPINVOKE.EIDMW_ERR_BAD_PATH_get();
  public static readonly int EIDMW_ERR_ALGO_BAD = beidlib_dotNetPINVOKE.EIDMW_ERR_ALGO_BAD_get();
  public static readonly int EIDMW_ERR_PIN_OPERATION = beidlib_dotNetPINVOKE.EIDMW_ERR_PIN_OPERATION_get();
  public static readonly int EIDMW_ERR_PIN_FORMAT = beidlib_dotNetPINVOKE.EIDMW_ERR_PIN_FORMAT_get();
  public static readonly int EIDMW_ERR_BAD_USAGE = beidlib_dotNetPINVOKE.EIDMW_ERR_BAD_USAGE_get();
  public static readonly int EIDMW_ERR_CARD = beidlib_dotNetPINVOKE.EIDMW_ERR_CARD_get();
  public static readonly int EIDMW_ERR_NOT_AUTHENTICATED = beidlib_dotNetPINVOKE.EIDMW_ERR_NOT_AUTHENTICATED_get();
  public static readonly int EIDMW_ERR_NOT_SUPPORTED = beidlib_dotNetPINVOKE.EIDMW_ERR_NOT_SUPPORTED_get();
  public static readonly int EIDMW_ERR_PIN_BAD = beidlib_dotNetPINVOKE.EIDMW_ERR_PIN_BAD_get();
  public static readonly int EIDMW_ERR_PIN_BLOCKED = beidlib_dotNetPINVOKE.EIDMW_ERR_PIN_BLOCKED_get();
  public static readonly int EIDMW_ERR_NO_CARD = beidlib_dotNetPINVOKE.EIDMW_ERR_NO_CARD_get();
  public static readonly int EIDMW_ERR_BAD_P1P2 = beidlib_dotNetPINVOKE.EIDMW_ERR_BAD_P1P2_get();
  public static readonly int EIDMW_ERR_CMD_NOT_ALLOWED = beidlib_dotNetPINVOKE.EIDMW_ERR_CMD_NOT_ALLOWED_get();
  public static readonly int EIDMW_ERR_FILE_NOT_FOUND = beidlib_dotNetPINVOKE.EIDMW_ERR_FILE_NOT_FOUND_get();
  public static readonly int EIDMW_ERR_APPLET_VERSION_NOT_FOUND = beidlib_dotNetPINVOKE.EIDMW_ERR_APPLET_VERSION_NOT_FOUND_get();
  public static readonly int EIDMW_ERR_NOT_ACTIVATED = beidlib_dotNetPINVOKE.EIDMW_ERR_NOT_ACTIVATED_get();
  public static readonly int EIDMW_ERR_CARD_COMM = beidlib_dotNetPINVOKE.EIDMW_ERR_CARD_COMM_get();
  public static readonly int EIDMW_ERR_NO_READER = beidlib_dotNetPINVOKE.EIDMW_ERR_NO_READER_get();
  public static readonly int EIDMW_ERR_PINPAD = beidlib_dotNetPINVOKE.EIDMW_ERR_PINPAD_get();
  public static readonly int EIDMW_ERR_CANT_CONNECT = beidlib_dotNetPINVOKE.EIDMW_ERR_CANT_CONNECT_get();
  public static readonly int EIDMW_ERR_CARD_RESET = beidlib_dotNetPINVOKE.EIDMW_ERR_CARD_RESET_get();
  public static readonly int EIDMW_ERR_CARD_SHARING = beidlib_dotNetPINVOKE.EIDMW_ERR_CARD_SHARING_get();
  public static readonly int EIDMW_ERR_NOT_TRANSACTED = beidlib_dotNetPINVOKE.EIDMW_ERR_NOT_TRANSACTED_get();
  public static readonly int EIDMW_ERR_LIMIT = beidlib_dotNetPINVOKE.EIDMW_ERR_LIMIT_get();
  public static readonly int EIDMW_ERR_CHECK = beidlib_dotNetPINVOKE.EIDMW_ERR_CHECK_get();
  public static readonly int EIDMW_ERR_PCSC_LIB = beidlib_dotNetPINVOKE.EIDMW_ERR_PCSC_LIB_get();
  public static readonly int EIDMW_ERR_ZLIB_RESOLVE = beidlib_dotNetPINVOKE.EIDMW_ERR_ZLIB_RESOLVE_get();
  public static readonly int EIDMW_ERR_UNKNOWN = beidlib_dotNetPINVOKE.EIDMW_ERR_UNKNOWN_get();
  public static readonly int EIDMW_PINPAD_ERR = beidlib_dotNetPINVOKE.EIDMW_PINPAD_ERR_get();
  public static readonly int EIDMW_CANT_LOAD_LIB = beidlib_dotNetPINVOKE.EIDMW_CANT_LOAD_LIB_get();
  public static readonly int EIDMW_ERR_MEMORY = beidlib_dotNetPINVOKE.EIDMW_ERR_MEMORY_get();
  public static readonly int EIDMW_ERR_DELETE_CACHE = beidlib_dotNetPINVOKE.EIDMW_ERR_DELETE_CACHE_get();
  public static readonly int EIDMW_CONF = beidlib_dotNetPINVOKE.EIDMW_CONF_get();
  public static readonly int EIDMW_CACHE_TAMPERED = beidlib_dotNetPINVOKE.EIDMW_CACHE_TAMPERED_get();
  public static readonly int EIDMW_ERR_SOCKET_CREATE = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_CREATE_get();
  public static readonly int EIDMW_ERR_SOCKET_SEND = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_SEND_get();
  public static readonly int EIDMW_ERR_SOCKET_RECV = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_RECV_get();
  public static readonly int EIDMW_ERR_SOCKET_GETHOST = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_GETHOST_get();
  public static readonly int EIDMW_ERR_SOCKET_CONNECT = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_CONNECT_get();
  public static readonly int EIDMW_ERR_SOCKET_SOCKET = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_SOCKET_get();
  public static readonly int EIDMW_ERR_SOCKET_BIND = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_BIND_get();
  public static readonly int EIDMW_ERR_SOCKET_ACCEPT = beidlib_dotNetPINVOKE.EIDMW_ERR_SOCKET_ACCEPT_get();
  public static readonly int EIDMW_ERR_PIN_CANCEL = beidlib_dotNetPINVOKE.EIDMW_ERR_PIN_CANCEL_get();
  public static readonly int EIDMW_ERR_TIMEOUT = beidlib_dotNetPINVOKE.EIDMW_ERR_TIMEOUT_get();
  public static readonly int EIDMW_NEW_PINS_DIFFER = beidlib_dotNetPINVOKE.EIDMW_NEW_PINS_DIFFER_get();
  public static readonly int EIDMW_WRONG_PIN_FORMAT = beidlib_dotNetPINVOKE.EIDMW_WRONG_PIN_FORMAT_get();
  public static readonly int EIDMW_WRONG_ASN1_FORMAT = beidlib_dotNetPINVOKE.EIDMW_WRONG_ASN1_FORMAT_get();
  public static readonly int EIDMW_FILE_NOT_OPENED = beidlib_dotNetPINVOKE.EIDMW_FILE_NOT_OPENED_get();
  public static readonly int EIDMW_PERMISSION_DENIED = beidlib_dotNetPINVOKE.EIDMW_PERMISSION_DENIED_get();
  public static readonly int EIDMW_INVALID_PATH = beidlib_dotNetPINVOKE.EIDMW_INVALID_PATH_get();
  public static readonly int EIDMW_TOO_MANY_OPENED_FILES = beidlib_dotNetPINVOKE.EIDMW_TOO_MANY_OPENED_FILES_get();
  public static readonly int EIDMW_DIR_NOT_OPENED = beidlib_dotNetPINVOKE.EIDMW_DIR_NOT_OPENED_get();
  public static readonly int EIDMW_INTERRUPTION = beidlib_dotNetPINVOKE.EIDMW_INTERRUPTION_get();
  public static readonly int EIDMW_OVERFLOW = beidlib_dotNetPINVOKE.EIDMW_OVERFLOW_get();
  public static readonly int EIDMW_ERROR_IO = beidlib_dotNetPINVOKE.EIDMW_ERROR_IO_get();
  public static readonly int EIDMW_ERR_LOGGER_APPLEAVING = beidlib_dotNetPINVOKE.EIDMW_ERR_LOGGER_APPLEAVING_get();
  public static readonly int EIDMW_ERR_DOCTYPE_UNKNOWN = beidlib_dotNetPINVOKE.EIDMW_ERR_DOCTYPE_UNKNOWN_get();
  public static readonly int EIDMW_ERR_CARDTYPE_BAD = beidlib_dotNetPINVOKE.EIDMW_ERR_CARDTYPE_BAD_get();
  public static readonly int EIDMW_ERR_CARDTYPE_UNKNOWN = beidlib_dotNetPINVOKE.EIDMW_ERR_CARDTYPE_UNKNOWN_get();
  public static readonly int EIDMW_ERR_CERT_NOISSUER = beidlib_dotNetPINVOKE.EIDMW_ERR_CERT_NOISSUER_get();
  public static readonly int EIDMW_ERR_RELEASE_NEEDED = beidlib_dotNetPINVOKE.EIDMW_ERR_RELEASE_NEEDED_get();
  public static readonly int EIDMW_ERR_BAD_TRANSACTION = beidlib_dotNetPINVOKE.EIDMW_ERR_BAD_TRANSACTION_get();
  public static readonly int EIDMW_ERR_FILETYPE_UNKNOWN = beidlib_dotNetPINVOKE.EIDMW_ERR_FILETYPE_UNKNOWN_get();
  public static readonly int EIDMW_ERR_CARD_CHANGED = beidlib_dotNetPINVOKE.EIDMW_ERR_CARD_CHANGED_get();
  public static readonly int EIDMW_ERR_READERSET_CHANGED = beidlib_dotNetPINVOKE.EIDMW_ERR_READERSET_CHANGED_get();
  public static readonly int EIDMW_ERR_NOT_ALLOW_BY_USER = beidlib_dotNetPINVOKE.EIDMW_ERR_NOT_ALLOW_BY_USER_get();
  public static readonly int EIDMW_ERR_CERT_NOCRL = beidlib_dotNetPINVOKE.EIDMW_ERR_CERT_NOCRL_get();
  public static readonly int EIDMW_ERR_CERT_NOOCSP = beidlib_dotNetPINVOKE.EIDMW_ERR_CERT_NOOCSP_get();
  public static readonly int EIDMW_ERR_CERT_NOROOT = beidlib_dotNetPINVOKE.EIDMW_ERR_CERT_NOROOT_get();
  public static readonly int EIDMW_ERR_USER_MUST_ANSWER = beidlib_dotNetPINVOKE.EIDMW_ERR_USER_MUST_ANSWER_get();
  public static readonly int EIDMW_ERR_SYSTEM = beidlib_dotNetPINVOKE.EIDMW_ERR_SYSTEM_get();
  public static readonly int EIDMW_ERR_SIGNAL = beidlib_dotNetPINVOKE.EIDMW_ERR_SIGNAL_get();
}

}
