/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Class for the info document.
/// You can get such an object from BEID_EIDCard::getVersionInfo() (or getDocument).
/// </summary>
public class BEID_CardVersionInfo : BEID_XMLDoc {
  private HandleRef swigCPtr;

  internal BEID_CardVersionInfo(IntPtr cPtr, bool cMemoryOwn) : base(beidlib_dotNetPINVOKE.BEID_CardVersionInfoUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BEID_CardVersionInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BEID_CardVersionInfo() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        beidlib_dotNetPINVOKE.delete_BEID_CardVersionInfo(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>Return the Serial Number of the card.</summary>
  public string getSerialNumber()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getSerialNumber(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the ComponenCode of the card.</summary>
  public string getComponentCode()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getComponentCode(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the OS Number of the card.</summary>
  public string getOsNumber()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getOsNumber(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the OS Version of the card.</summary>
  public string getOsVersion()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getOsVersion(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the Softmask Number of the card.</summary>
  public string getSoftmaskNumber()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getSoftmaskNumber(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the Softmask Version of the card.</summary>
  public string getSoftmaskVersion()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getSoftmaskVersion(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the Applet Version of the card.</summary>
  public string getAppletVersion()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getAppletVersion(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the Global Os Version of the card.</summary>
  public string getGlobalOsVersion()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getGlobalOsVersion(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the Applet Interface Version of the card.</summary>
  public string getAppletInterfaceVersion()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getAppletInterfaceVersion(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the PKCS#1 Support of the card.</summary>
  public string getPKCS1Support()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getPKCS1Support(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the Key Exchange Version of the card.</summary>
  public string getKeyExchangeVersion()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getKeyExchangeVersion(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the Applet Life Cycle of the card.</summary>
  public string getAppletLifeCycle()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getAppletLifeCycle(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return field GraphicalPersonalisation from the TokenInfo file.</summary>
  public string getGraphicalPersonalisation()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getGraphicalPersonalisation(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return field ElectricalPersonalisation from the TokenInfo file.</summary>
  public string getElectricalPersonalisation()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getElectricalPersonalisation(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return field ElectricalPersonalisationInterface from the TokenInfo file.</summary>
  public string getElectricalPersonalisationInterface()
  {
    string ret = beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getElectricalPersonalisationInterface(swigCPtr);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Return the signature of the card info.</summary>
  public BEID_ByteArray getSignature()
  {
    BEID_ByteArray ret = new BEID_ByteArray(beidlib_dotNetPINVOKE.BEID_CardVersionInfo_getSignature(swigCPtr), false);
    if (beidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw beidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
