/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

public enum BEID_FileType {
  BEID_FILETYPE_UNKNOWN = 0,
  BEID_FILETYPE_TLV,
  BEID_FILETYPE_XML,
  BEID_FILETYPE_CSV
}

}
