/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.belgium.eid {

public enum BEID_CardType {

    /// <summary>Unknown card</summary>
    BEID_CARDTYPE_UNKNOWN = 0,

    /// <summary>Normal eid card</summary>
    BEID_CARDTYPE_EID,

    /// <summary>Kids eid card</summary>  
    BEID_CARDTYPE_KIDS,

    /// <summary>Foreigner eid card</summary>
    BEID_CARDTYPE_FOREIGNER,

    /// <summary>Sis card</summary>
    BEID_CARDTYPE_SIS           
}

}
