package be.belgium.eid;

class eidlibJNI
{
  public final static native int get_BEID_Status_general(long jarg1);
  public final static native int get_BEID_Status_system(long jarg1);
  public final static native int get_BEID_Status_pcsc(long jarg1);
  public final static native byte[] get_BEID_Status_cardSW(long jarg1);
  public final static native long new_BEID_Status();
  public final static native void delete_BEID_Status(long jarg1);
  public final static native byte[] get_BEID_Certif_certif(long jarg1);
  public final static native String get_BEID_Certif_certifLabel(long jarg1);
  public final static native int get_BEID_Certif_certifStatus(long jarg1);
  public final static native long new_BEID_Certif();
  public final static native void delete_BEID_Certif(long jarg1);
  public final static native int get_BEID_Certif_Check_usedPolicy(long jarg1);
  public final static native long get_BEID_Certif_Check_certificate(long jarg1, int jarg2);
  public final static native int get_BEID_Certif_Check_certificatesLength(long jarg1);
  public final static native int get_BEID_Certif_Check_signatureCheck(long jarg1);
  public final static native long new_BEID_Certif_Check();
  public final static native void delete_BEID_Certif_Check(long jarg1);
  public final static native void set_BEID_Pin_pinType(long jarg1, int jarg2);
  public final static native void set_BEID_Pin_id(long jarg1, short jarg2);
  public final static native void set_BEID_Pin_usageCode(long jarg1, int jarg2);
  public final static native void set_BEID_Pin_shortUsage(long jarg1, String jarg2);
  public final static native void set_BEID_Pin_longUsage(long jarg1, String jarg2);
  public final static native long new_BEID_Pin();
  public final static native void delete_BEID_Pin(long jarg1);
  public final static native short get_BEID_ID_Data_version(long jarg1);
  public final static native String get_BEID_ID_Data_cardNumber(long jarg1);
  public final static native String get_BEID_ID_Data_chipNumber(long jarg1);
  public final static native String get_BEID_ID_Data_validityDateBegin(long jarg1);
  public final static native String get_BEID_ID_Data_validityDateEnd(long jarg1);
  public final static native String get_BEID_ID_Data_municipality(long jarg1);
  public final static native String get_BEID_ID_Data_nationalNumber(long jarg1);
  public final static native String get_BEID_ID_Data_name(long jarg1);
  public final static native String get_BEID_ID_Data_firstName1(long jarg1);
  public final static native String get_BEID_ID_Data_firstName2(long jarg1);
  public final static native String get_BEID_ID_Data_firstName3(long jarg1);
  public final static native String get_BEID_ID_Data_nationality(long jarg1);
  public final static native String get_BEID_ID_Data_birthLocation(long jarg1);
  public final static native String get_BEID_ID_Data_birthDate(long jarg1);
  public final static native String get_BEID_ID_Data_sex(long jarg1);
  public final static native String get_BEID_ID_Data_nobleCondition(long jarg1);
  public final static native int get_BEID_ID_Data_documentType(long jarg1);
  public final static native boolean get_BEID_ID_Data_whiteCane(long jarg1);
  public final static native boolean get_BEID_ID_Data_yellowCane(long jarg1);
  public final static native boolean get_BEID_ID_Data_extendedMinority(long jarg1);
  public final static native byte[] get_BEID_ID_Data_hashPhoto(long jarg1);
  public final static native long new_BEID_ID_Data();
  public final static native void delete_BEID_ID_Data(long jarg1);
  public final static native short get_BEID_Address_version(long jarg1);
  public final static native String get_BEID_Address_street(long jarg1);
  public final static native String get_BEID_Address_streetNumber(long jarg1);
  public final static native String get_BEID_Address_boxNumber(long jarg1);
  public final static native String get_BEID_Address_zip(long jarg1);
  public final static native String get_BEID_Address_municipality(long jarg1);
  public final static native String get_BEID_Address_country(long jarg1);
  public final static native long new_BEID_Address();
  public final static native void delete_BEID_Address(long jarg1);
  public final static native byte[] get_BEID_VersionInfo_SerialNumber(long jarg1);
  public final static native short get_BEID_VersionInfo_ComponentCode(long jarg1);
  public final static native short get_BEID_VersionInfo_OSNumber(long jarg1);
  public final static native short get_BEID_VersionInfo_OSVersion(long jarg1);
  public final static native short get_BEID_VersionInfo_SoftmaskNumber(long jarg1);
  public final static native short get_BEID_VersionInfo_SoftmaskVersion(long jarg1);
  public final static native short get_BEID_VersionInfo_AppletVersion(long jarg1);
  public final static native int get_BEID_VersionInfo_GlobalOSVersion(long jarg1);
  public final static native short get_BEID_VersionInfo_AppletInterfaceVersion(long jarg1);
  public final static native short get_BEID_VersionInfo_PKCS1Support(long jarg1);
  public final static native short get_BEID_VersionInfo_KeyExchangeVersion(long jarg1);
  public final static native short get_BEID_VersionInfo_ApplicationLifeCycle(long jarg1);
  public final static native short get_BEID_VersionInfo_GraphPerso(long jarg1);
  public final static native short get_BEID_VersionInfo_ElecPerso(long jarg1);
  public final static native short get_BEID_VersionInfo_ElecPersoInterface(long jarg1);
  public final static native short get_BEID_VersionInfo_Reserved(long jarg1);
  public final static native long new_BEID_VersionInfo();
  public final static native void delete_BEID_VersionInfo(long jarg1);
  public final static native byte[] get_BEID_Bytes_data(long jarg1);
  public final static native long new_BEID_Bytes();
  public final static native void delete_BEID_Bytes(long jarg1);
  public final static native long get_BEID_Long_data(long jarg1);
  public final static native long new_BEID_Long();
  public final static native void delete_BEID_Long(long jarg1);
  public final static native void set_BEID_Raw_idData(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_idData(long jarg1);
  public final static native void set_BEID_Raw_idSigData(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_idSigData(long jarg1);
  public final static native void set_BEID_Raw_addrData(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_addrData(long jarg1);
  public final static native void set_BEID_Raw_addrSigData(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_addrSigData(long jarg1);
  public final static native void set_BEID_Raw_pictureData(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_pictureData(long jarg1);
  public final static native void set_BEID_Raw_cardData(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_cardData(long jarg1);
  public final static native void set_BEID_Raw_tokenInfo(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_tokenInfo(long jarg1);
  public final static native void set_BEID_Raw_certRN(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_certRN(long jarg1);
  public final static native void set_BEID_Raw_challenge(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_challenge(long jarg1);
  public final static native void set_BEID_Raw_response(long jarg1, byte[] jarg2);
  public final static native byte[] get_BEID_Raw_response(long jarg1);
  public final static native long new_BEID_Raw();
  public final static native void delete_BEID_Raw(long jarg1);
  public final static native long BEID_Init(String jarg1, int jarg2, int jarg3, long jarg4);
  public final static native long BEID_Exit();
  public final static native long BEID_GetID(long jarg1, long jarg2);
  public final static native long BEID_GetAddress(long jarg1, long jarg2);
  public final static native long BEID_GetPicture(long jarg1, long jarg2);
  public final static native long BEID_GetRawData(long jarg1);
  public final static native long BEID_SetRawData(long jarg1);
  public final static native long BEID_GetVersionInfo(long jarg1, int jarg2,long jarg3);
  public final static native long BEID_BeginTransaction();
  public final static native long BEID_EndTransaction();
  public final static native long BEID_SelectApplication(byte[] jarg1);
  public final static native long BEID_VerifyPIN(long jarg1, String jarg2, long jarg3);
  public final static native long BEID_ChangePIN(long jarg1, String jarg2, String jarg3, long jarg4);
  public final static native long BEID_GetPINStatus(long jarg1, long jarg2, int jarg3, long jarg4);
  public final static native long BEID_ReadFile(byte[] jarg1, long jarg2, long jarg3);
  public final static native long BEID_WriteFile(byte[] jarg1, byte[] jarg2, long jarg3);
  public final static native long BEID_FlushCache();
  public final static native long BEID_SendAPDU(byte[] jarg1, long jarg2, long jarg3);
}
