/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * This class represents a Belgium EID card.
  * \see BEID_ReaderContext.getEIDCard()
  *********************************************************************************/
public class BEID_EIDCard extends BEID_SmartCard {
  private long swigCPtr;

  protected BEID_EIDCard(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_EIDCardUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_EIDCard obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_EIDCard(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

	/** Return true if the user allowed the application to read the card */
  public static boolean isApplicationAllowed() throws java.lang.Exception {
    return beidlibJava_WrapperJNI.BEID_EIDCard_isApplicationAllowed();
  }

	/** Return true if this is a test card */
  public boolean isTestCard() throws java.lang.Exception {
    return beidlibJava_WrapperJNI.BEID_EIDCard_isTestCard(swigCPtr, this);
  }

	/** Return true if test cards are allowed */
  public boolean getAllowTestCard() throws java.lang.Exception {
    return beidlibJava_WrapperJNI.BEID_EIDCard_getAllowTestCard(swigCPtr, this);
  }

	/** Set the flag to allow test cards */
  public void setAllowTestCard(boolean allow) throws java.lang.Exception {
    beidlibJava_WrapperJNI.BEID_EIDCard_setAllowTestCard(swigCPtr, this, allow);
  }

 	/**
	  * Return the status of the data.
	  * (RRN certificate validity)
	  */
  public BEID_CertifStatus getDataStatus() throws java.lang.Exception {
    return BEID_CertifStatus.swigToEnum(beidlibJava_WrapperJNI.BEID_EIDCard_getDataStatus(swigCPtr, this));
  }

	/**
	 * Return a document from the card.
	 * Throw BEID_ExDocTypeUnknown exception if the document doesn't exist for this card
	 */
  public BEID_XMLDoc getDocument(BEID_DocumentType type) throws java.lang.Exception {
    return new BEID_XMLDoc(beidlibJava_WrapperJNI.BEID_EIDCard_getDocument(swigCPtr, this, type.swigValue()), false);
  }

	/** Get the full document */
  public BEID_EIdFullDoc getFullDoc() throws java.lang.Exception {
    return new BEID_EIdFullDoc(beidlibJava_WrapperJNI.BEID_EIDCard_getFullDoc(swigCPtr, this), false);
  }

	/** Get the id document */
  public BEID_EId getID() throws java.lang.Exception {
    return new BEID_EId(beidlibJava_WrapperJNI.BEID_EIDCard_getID(swigCPtr, this), false);
  }

	/** Get the picture document */
  public BEID_Picture getPicture() throws java.lang.Exception {
    return new BEID_Picture(beidlibJava_WrapperJNI.BEID_EIDCard_getPicture(swigCPtr, this), false);
  }

	/** Get the info document  */
  public BEID_CardVersionInfo getVersionInfo() throws java.lang.Exception {
    return new BEID_CardVersionInfo(beidlibJava_WrapperJNI.BEID_EIDCard_getVersionInfo(swigCPtr, this), false);
  }

	/** Return certificate by type from the card */
  public BEID_Certificate getCert(BEID_CertifType type) throws java.lang.Exception {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_EIDCard_getCert(swigCPtr, this, type.swigValue()), false);
  }

	/** Return the RRN certificate from the card */
  public BEID_Certificate getRrn() {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_EIDCard_getRrn(swigCPtr, this), false);
  }

	/** Return the root certificate from the card */
  public BEID_Certificate getRoot() throws java.lang.Exception {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_EIDCard_getRoot(swigCPtr, this), false);
  }

	/** Return the ca certificate from the card */
  public BEID_Certificate getCA() throws java.lang.Exception {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_EIDCard_getCA(swigCPtr, this), false);
  }

	/** Return the signature certificate from the card */
  public BEID_Certificate getSignature() throws java.lang.Exception {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_EIDCard_getSignature(swigCPtr, this), false);
  }

	/** Return the authentication certificate from the card */
  public BEID_Certificate getAuthentication() throws java.lang.Exception {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_EIDCard_getAuthentication(swigCPtr, this), false);
  }

	/**
	 * Return a raw data from the card.
	 * Throw BEID_ExFileTypeUnknown exception if the document doesn't exist for this card
	 */
  public BEID_ByteArray getRawData(BEID_RawDataType type) throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData(swigCPtr, this, type.swigValue()), false);
  }

	/** Get the Id raw data */
  public BEID_ByteArray getRawData_Id() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_Id(swigCPtr, this), false);
  }

	/** Get the IdSig raw data */
  public BEID_ByteArray getRawData_IdSig() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_IdSig(swigCPtr, this), false);
  }

	/** Get the address raw data */
  public BEID_ByteArray getRawData_Addr() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_Addr(swigCPtr, this), false);
  }

	/** Get the AddrSig raw data */
  public BEID_ByteArray getRawData_AddrSig() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_AddrSig(swigCPtr, this), false);
  }

	/** Get the picture raw data */
  public BEID_ByteArray getRawData_Picture() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_Picture(swigCPtr, this), false);
  }

	/** Get the Card Info raw data */
  public BEID_ByteArray getRawData_CardInfo() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_CardInfo(swigCPtr, this), false);
  }

	/** Get the Token Info raw data */
  public BEID_ByteArray getRawData_TokenInfo() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_TokenInfo(swigCPtr, this), false);
  }

	/** Get the Cert RRN raw data */
  public BEID_ByteArray getRawData_CertRRN() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_CertRRN(swigCPtr, this), false);
  }

	/** Get the challenge raw data */
  public BEID_ByteArray getRawData_Challenge() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_Challenge(swigCPtr, this), false);
  }

	/** Get the response raw data */
  public BEID_ByteArray getRawData_Response() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EIDCard_getRawData_Response(swigCPtr, this), false);
  }

}
