/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Exception class File Type Unknown (error code = EIDMW_ERR_FILETYPE_UNKNOWN)
  *
  *	Thrown when the Raw Data type doesn't exist for this card
  * Used in : - BEID_Card.getRawData(BEID_RawDataType type)
  *********************************************************************************/
public class BEID_ExFileTypeUnknown extends BEID_Exception {
  private long swigCPtr;

  protected BEID_ExFileTypeUnknown(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_ExFileTypeUnknownUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_ExFileTypeUnknown obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_ExFileTypeUnknown(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

	/** Constructor */
  public BEID_ExFileTypeUnknown() {
    this(beidlibJava_WrapperJNI.new_BEID_ExFileTypeUnknown(), true);
  }

}
