/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Exception class Certificate No OCSP responder (error code = EIDMW_ERR_CERT_NOOCSP)
  *
  *	Thrown when asked for the OCSP response when there is no responder
  * Used in : - BEID_Certificate.getOcspResponse()
  *********************************************************************************/
public class BEID_ExCertNoOcsp extends BEID_Exception {
  private long swigCPtr;

  protected BEID_ExCertNoOcsp(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_ExCertNoOcspUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_ExCertNoOcsp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_ExCertNoOcsp(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

	/** Constructor */
  public BEID_ExCertNoOcsp() {
    this(beidlibJava_WrapperJNI.new_BEID_ExCertNoOcsp(), true);
  }

}
