/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Class that holds the possible validation levels for CRL or OCSP validation
  *********************************************************************************/
public final class BEID_ValidationLevel {
	/**
	* no validation
	*/
  public final static BEID_ValidationLevel BEID_VALIDATION_LEVEL_NONE = new BEID_ValidationLevel("BEID_VALIDATION_LEVEL_NONE", beidlibJava_WrapperJNI.BEID_VALIDATION_LEVEL_NONE_get());
	/**
	* optional validation
	*/
  public final static BEID_ValidationLevel BEID_VALIDATION_LEVEL_OPTIONAL = new BEID_ValidationLevel("BEID_VALIDATION_LEVEL_OPTIONAL");
	/**
	* mandatory validation
	*/
  public final static BEID_ValidationLevel BEID_VALIDATION_LEVEL_MANDATORY = new BEID_ValidationLevel("BEID_VALIDATION_LEVEL_MANDATORY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BEID_ValidationLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BEID_ValidationLevel.class + " with value " + swigValue);
  }

  private BEID_ValidationLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BEID_ValidationLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BEID_ValidationLevel(String swigName, BEID_ValidationLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BEID_ValidationLevel[] swigValues = { BEID_VALIDATION_LEVEL_NONE, BEID_VALIDATION_LEVEL_OPTIONAL, BEID_VALIDATION_LEVEL_MANDATORY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

