/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Exception class Readerset changed (error code = EIDMW_ERR_READERSET_CHANGED)
  *
  *	Thrown when accessing a card object but the readerset has been changed
  * Used in : - BEID_Object.checkContextStillOk()
  *********************************************************************************/
public class BEID_ExReaderSetChanged extends BEID_Exception {
  private long swigCPtr;

  protected BEID_ExReaderSetChanged(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_ExReaderSetChangedUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_ExReaderSetChanged obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_ExReaderSetChanged(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

	/** Constructor */
  public BEID_ExReaderSetChanged() {
    this(beidlibJava_WrapperJNI.new_BEID_ExReaderSetChanged(), true);
  }

}
