/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Class that holds the different PIN uasage definitions
  *********************************************************************************/
public final class BEID_PinUsage {
	/** Pin usage unknown */
  public final static BEID_PinUsage BEID_PIN_USG_UNKNOWN = new BEID_PinUsage("BEID_PIN_USG_UNKNOWN");
	/** Pin usage authentication */
  public final static BEID_PinUsage BEID_PIN_USG_AUTH = new BEID_PinUsage("BEID_PIN_USG_AUTH");
	/** Pin usage signature */
  public final static BEID_PinUsage BEID_PIN_USG_SIGN = new BEID_PinUsage("BEID_PIN_USG_SIGN");
	/** Pin usage address */
  public final static BEID_PinUsage BEID_PIN_USG_ADDRESS = new BEID_PinUsage("BEID_PIN_USG_ADDRESS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BEID_PinUsage swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BEID_PinUsage.class + " with value " + swigValue);
  }

  private BEID_PinUsage(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BEID_PinUsage(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BEID_PinUsage(String swigName, BEID_PinUsage swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BEID_PinUsage[] swigValues = { BEID_PIN_USG_UNKNOWN, BEID_PIN_USG_AUTH, BEID_PIN_USG_SIGN, BEID_PIN_USG_ADDRESS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

