/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

public final class BEID_RawDataType {
  public final static BEID_RawDataType BEID_RAWDATA_ID = new BEID_RawDataType("BEID_RAWDATA_ID", beidlibJava_WrapperJNI.BEID_RAWDATA_ID_get());
  public final static BEID_RawDataType BEID_RAWDATA_ID_SIG = new BEID_RawDataType("BEID_RAWDATA_ID_SIG");
  public final static BEID_RawDataType BEID_RAWDATA_ADDR = new BEID_RawDataType("BEID_RAWDATA_ADDR");
  public final static BEID_RawDataType BEID_RAWDATA_ADDR_SIG = new BEID_RawDataType("BEID_RAWDATA_ADDR_SIG");
  public final static BEID_RawDataType BEID_RAWDATA_PICTURE = new BEID_RawDataType("BEID_RAWDATA_PICTURE");
  public final static BEID_RawDataType BEID_RAWDATA_CARD_INFO = new BEID_RawDataType("BEID_RAWDATA_CARD_INFO");
  public final static BEID_RawDataType BEID_RAWDATA_TOKEN_INFO = new BEID_RawDataType("BEID_RAWDATA_TOKEN_INFO");
  public final static BEID_RawDataType BEID_RAWDATA_CERT_RRN = new BEID_RawDataType("BEID_RAWDATA_CERT_RRN");
  public final static BEID_RawDataType BEID_RAWDATA_CHALLENGE = new BEID_RawDataType("BEID_RAWDATA_CHALLENGE");
  public final static BEID_RawDataType BEID_RAWDATA_RESPONSE = new BEID_RawDataType("BEID_RAWDATA_RESPONSE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BEID_RawDataType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BEID_RawDataType.class + " with value " + swigValue);
  }

  private BEID_RawDataType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BEID_RawDataType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BEID_RawDataType(String swigName, BEID_RawDataType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BEID_RawDataType[] swigValues = { BEID_RAWDATA_ID, BEID_RAWDATA_ID_SIG, BEID_RAWDATA_ADDR, BEID_RAWDATA_ADDR_SIG, BEID_RAWDATA_PICTURE, BEID_RAWDATA_CARD_INFO, BEID_RAWDATA_TOKEN_INFO, BEID_RAWDATA_CERT_RRN, BEID_RAWDATA_CHALLENGE, BEID_RAWDATA_RESPONSE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

