/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * This class represents a Foreigner card which is a particular BEID_EIDCard
  * \see BEID_ReaderContext.getForeignerCard()
  *********************************************************************************/
public class BEID_ForeignerCard extends BEID_EIDCard {
  private long swigCPtr;

  protected BEID_ForeignerCard(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_ForeignerCardUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_ForeignerCard obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_ForeignerCard(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

}
