/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Exception class Not allow by user (error code = EIDMW_ERR_NOT_ALLOW_BY_USER)
  *
  *	Thrown when the user didn't allow to read the card data
  *********************************************************************************/
public class BEID_ExNotAllowByUser extends BEID_Exception {
  private long swigCPtr;

  protected BEID_ExNotAllowByUser(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_ExNotAllowByUserUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_ExNotAllowByUser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_ExNotAllowByUser(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

	/** Constructor */
  public BEID_ExNotAllowByUser() {
    this(beidlibJava_WrapperJNI.new_BEID_ExNotAllowByUser(), true);
  }

}
