/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

public class BEID_RawData_Sis {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BEID_RawData_Sis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_RawData_Sis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_RawData_Sis(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setIdData(BEID_ByteArray value) {
    beidlibJava_WrapperJNI.BEID_RawData_Sis_idData_set(swigCPtr, this, BEID_ByteArray.getCPtr(value), value);
  }

  public BEID_ByteArray getIdData() {
    long cPtr = beidlibJava_WrapperJNI.BEID_RawData_Sis_idData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BEID_ByteArray(cPtr, false);
  }

  public BEID_RawData_Sis() {
    this(beidlibJava_WrapperJNI.new_BEID_RawData_Sis(), true);
  }

}
