/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Exception class Certificate No CRL (error code = EIDMW_ERR_CERT_NOCRL)
  *
  *	Thrown when ask for the CRL when the certificate contains no CDP
  * Used in : - BEID_Certificate::getCrl()
  *********************************************************************************/
public class BEID_ExCertNoCrl extends BEID_Exception {
  private long swigCPtr;

  protected BEID_ExCertNoCrl(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_ExCertNoCrlUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_ExCertNoCrl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_ExCertNoCrl(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

	/** Constructor */
  public BEID_ExCertNoCrl() {
    this(beidlibJava_WrapperJNI.new_BEID_ExCertNoCrl(), true);
  }

}
