/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Class that holds the possible validation processes to be used
  *********************************************************************************/
public final class BEID_ValidationProcess {
	/**
	* no validation process
	*/
  public final static BEID_ValidationProcess BEID_VALIDATION_PROCESS_NONE = new BEID_ValidationProcess("BEID_VALIDATION_PROCESS_NONE", beidlibJava_WrapperJNI.BEID_VALIDATION_PROCESS_NONE_get());
	/**
	* CRL validation
	*/
  public final static BEID_ValidationProcess BEID_VALIDATION_PROCESS_CRL = new BEID_ValidationProcess("BEID_VALIDATION_PROCESS_CRL");
	/**
	* OCSP validation
	*/
  public final static BEID_ValidationProcess BEID_VALIDATION_PROCESS_OCSP = new BEID_ValidationProcess("BEID_VALIDATION_PROCESS_OCSP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BEID_ValidationProcess swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BEID_ValidationProcess.class + " with value " + swigValue);
  }

  private BEID_ValidationProcess(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BEID_ValidationProcess(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BEID_ValidationProcess(String swigName, BEID_ValidationProcess swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BEID_ValidationProcess[] swigValues = { BEID_VALIDATION_PROCESS_NONE, BEID_VALIDATION_PROCESS_CRL, BEID_VALIDATION_PROCESS_OCSP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

