/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * This class represents a SIS card.
  * To get this object: BEID_ReaderContext.getSISCard()
  *********************************************************************************/
public class BEID_SISCard extends BEID_MemoryCard {
  private long swigCPtr;

  protected BEID_SISCard(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_SISCardUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_SISCard obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_SISCard(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

 	/**
	 * Return a document from the card.
	 * Throws BEID_ExDocTypeUnknown exception if the document doesn't exist for this card
	 */
  public BEID_XMLDoc getDocument(BEID_DocumentType type) throws java.lang.Exception {
    return new BEID_XMLDoc(beidlibJava_WrapperJNI.BEID_SISCard_getDocument(swigCPtr, this, type.swigValue()), false);
  }
	/** Get the full document */
  public BEID_SisFullDoc getFullDoc() throws java.lang.Exception {
    return new BEID_SisFullDoc(beidlibJava_WrapperJNI.BEID_SISCard_getFullDoc(swigCPtr, this), false);
  }
	/** Get the id document */
  public BEID_SisId getID() throws java.lang.Exception {
    return new BEID_SisId(beidlibJava_WrapperJNI.BEID_SISCard_getID(swigCPtr, this), false);
  }

 	/**
	 * Return raw data from the card.
	 * Throws BEID_ExFileTypeUnknown exception if the document doesn't exist for this card
	 */
  public BEID_ByteArray getRawData(BEID_RawDataType type) throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_SISCard_getRawData(swigCPtr, this, type.swigValue()), false);
  }
	/** Get the id RawData from the card. */
  public BEID_ByteArray getRawData_Id() throws java.lang.Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_SISCard_getRawData_Id(swigCPtr, this), false);
  }

}
