/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

/******************************************************************************//**
  * Class that holds the different log level definitions
  *********************************************************************************/
public final class BEID_LogLevel {
	/**
	 * log level: critical
	 */
  public final static BEID_LogLevel BEID_LOG_LEVEL_CRITICAL = new BEID_LogLevel("BEID_LOG_LEVEL_CRITICAL");
	/**
	 * log level: error
	 */
  public final static BEID_LogLevel BEID_LOG_LEVEL_ERROR = new BEID_LogLevel("BEID_LOG_LEVEL_ERROR");
	/**
	 * log level: warning
	 */
  public final static BEID_LogLevel BEID_LOG_LEVEL_WARNING = new BEID_LogLevel("BEID_LOG_LEVEL_WARNING");
	/**
	 * log level: info
	 */
  public final static BEID_LogLevel BEID_LOG_LEVEL_INFO = new BEID_LogLevel("BEID_LOG_LEVEL_INFO");
	/**
	 * log level: debug
	 */
  public final static BEID_LogLevel BEID_LOG_LEVEL_DEBUG = new BEID_LogLevel("BEID_LOG_LEVEL_DEBUG");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BEID_LogLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BEID_LogLevel.class + " with value " + swigValue);
  }

  private BEID_LogLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BEID_LogLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BEID_LogLevel(String swigName, BEID_LogLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BEID_LogLevel[] swigValues = { BEID_LOG_LEVEL_CRITICAL, BEID_LOG_LEVEL_ERROR, BEID_LOG_LEVEL_WARNING, BEID_LOG_LEVEL_INFO, BEID_LOG_LEVEL_DEBUG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

