include ../_Builds/archs.mac     # for $(EXTRA_DEF) and $(ARCHS)
include ../_Builds/versions.mak

TARGET = ../_Binaries/libproxy_pcsclite.dylib.$(PROXY_LIB_VERSION)

OBJS1 = ../EidTestinfraLib/Logger.o ../EidTestinfraLib/controlFileAccess.o \
	../EidTestinfraLib/virtualCardAccess.o ../EidTestinfraLib/Mutex.o \
	../EidTestinfraLib/util.o ../EidTestinfraLib/xml.o
OBJS2 =	APDURequest.o FileStructure.o SoftReader.o WinscardImpl.o \
	Carddata.o HexUtils.o SoftReaderManager.o proxy_pcsclite.o \
	Control.o SoftCard.o Transaction.o

CPPFLAGS = -Wall -O3 $(ARCHS) -Wno-deprecated-declarations $(EXTRA_DEF)
INCLUDE = -I. -I../EidTestinfraLib -I/System/Library/Frameworks/PCSC.framework/Headers
LIBS = -ldl -lpthread -W,-framework -W,PCSC
LFLAGS = -fPIC -headerpad_max_install_names -single_module -dynamiclib -compatibility_version 1.0.0

all: $(TARGET)

clean:
	- rm $(OBJS1) $(OBJS2) $(TARGET)

$(TARGET): $(OBJS1) $(OBJS2)
	g++ $(LFLAGS) -o $(TARGET) $(OBJS1) $(OBJS2) $(LIBS)	

%.o: %.cpp *.h
	g++ -c $(INCLUDE) $(CPPFLAGS) $< -o $@

../EidTestinfraLib/%.o: ../EidTestinfraLib/%.cpp ../EidTestinfraLib/*.h
	g++ -c $(INCLUDE) $(CPPFLAGS) $< -o $@
