import os

Import('env')
myenv = env.Copy()

# if using os.environ then as root will never be installed !
#javaHome = os.environ['JAVA_HOME']
javaHome = env['JAVA']
obj = myenv.genobj('shlib', myenv)
obj.target='libbeidlibjni'
obj.src = Split('eidlib_wrap.cpp MyApp.cpp')
obj.vnum='2.7.2'
obj.libs='beid'
obj.libpaths='../eidlib'
obj.includes='../eidlib ' + javaHome + '/include ' + javaHome + '/include/linux'
obj.execute()
libdir = env['LIBDIR']
env.Alias('install', env.Install(libdir, obj.target + '.so.' + obj.vnum))
env.Alias('install', env.Install(libdir, obj.target + '.so'))
