#!/bin/bash
file=$1
prefix=$2
var=`basename $file`
var=${var//-/_}
var=${var//./_}
echo "static unsigned char ${prefix}${var}[] = {"
hexdump -v -e '" " 16/1 "0x%02x," "\n"' ${file} | sed -e '$s/0x  ,//g' | sed -e '$s/,$//'
echo "};"

