######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 7 17:44:09 2008
######################################################################


include(../_Builds/eidcommon.mak)

TEMPLATE = app
TARGET =  $${EIDLIBTEST}
VERSION = $${EIDLIBTEST_MAJ}.$${EIDLIBTEST_MIN}.$${EIDLIBTEST_REV}

message("Compile $$TARGET")

###
### Installation setup
###
target.path = $${INSTALL_DIR_BIN}
INSTALLS += target

###
### Compiler setup
###

CONFIG += debug
CONFIG -= warn_on qt

## destination directory for the compiler
DESTDIR = ../bin

DEFINES+= EIDLIB_EXPORTS

DEPENDPATH += .
INCLUDEPATH += . ../eidlib \
		../eidlibC \
		../applayer \
		../common \
		../cardlayer \
                $${PCSC_INCLUDE_DIR}


LIBS += -L../lib  \
        -l$${CARDLAYEREMULIB}  \
        -l$${APPLAYEREMULIB} \
        -l$${COMMONLIB} \
        -l$${DLGLIB}

unix:!macx:LIBS += -Wl,-R,"'\$\$ORIGIN/$${LINK_RELATIVE_PATH}'"

BUILD_TESTS=yes ## needed by ../_Builds/eidtests.mak
include(../_Builds/eidtests.mak)

## for these tests we always use the cardlayer emulator
EMULATE_CARDLAYER=yes

## flag recommended by ld for this exe
macx: QMAKE_LFLAGS +=  -bind_at_load

# Input

SOURCES += eidlibCardTest.cpp \
           eidlibCryptoTest.cpp \
           eidlibDocTest.cpp \
           eidlibOldTest.cpp \
           eidlibReaderTest.cpp \
           eidlibTest.cpp \
	   ../eidlib/eidlibCard.cpp \
	   ../eidlib/eidlibCrypto.cpp \
	   ../eidlib/eidlibDoc.cpp \
	   ../eidlibC/eidlibOld.cpp \
	   ../eidlib/eidlibReader.cpp \
           ../eidlib/eidlibException.cpp \
           ../eidlib/InternalUtil.cpp


HEADERS += ../eidlib/eidlib.h \
   ../eidlibC/eidlibC.h     \  
   ../eidlibC/eidlibCdefines.h \
   ../eidlib/eidlibdefines.h \
   ../eidlib/eidlibException.h \
   ../eidlib/InternalUtil.h
   

