/*
 * Copyright (c) 2011,2015 Apple Inc. All rights reserved.
 * 
 * corecrypto Internal Use License Agreement
 * 
 * IMPORTANT:  This Apple corecrypto software is supplied to you by Apple Inc. ("Apple")
 * in consideration of your agreement to the following terms, and your download or use
 * of this Apple software constitutes acceptance of these terms.  If you do not agree
 * with these terms, please do not download or use this Apple software.
 * 
 * 1.	As used in this Agreement, the term "Apple Software" collectively means and
 * includes all of the Apple corecrypto materials provided by Apple here, including
 * but not limited to the Apple corecrypto software, frameworks, libraries, documentation
 * and other Apple-created materials. In consideration of your agreement to abide by the
 * following terms, conditioned upon your compliance with these terms and subject to
 * these terms, Apple grants you, for a period of ninety (90) days from the date you
 * download the Apple Software, a limited, non-exclusive, non-sublicensable license
 * under Apple’s copyrights in the Apple Software to make a reasonable number of copies
 * of, compile, and run the Apple Software internally within your organization only on
 * devices and computers you own or control, for the sole purpose of verifying the
 * security characteristics and correct functioning of the Apple Software; provided
 * that you must retain this notice and the following text and disclaimers in all
 * copies of the Apple Software that you make. You may not, directly or indirectly,
 * redistribute the Apple Software or any portions thereof. The Apple Software is only
 * licensed and intended for use as expressly stated above and may not be used for other
 * purposes or in other contexts without Apple's prior written permission.  Except as
 * expressly stated in this notice, no other rights or licenses, express or implied, are
 * granted by Apple herein.
 * 
 * 2.	The Apple Software is provided by Apple on an "AS IS" basis.  APPLE MAKES NO
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES
 * OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, REGARDING
 * THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS,
 * SYSTEMS, OR SERVICES. APPLE DOES NOT WARRANT THAT THE APPLE SOFTWARE WILL MEET YOUR
 * REQUIREMENTS, THAT THE OPERATION OF THE APPLE SOFTWARE WILL BE UNINTERRUPTED OR
 * ERROR-FREE, THAT DEFECTS IN THE APPLE SOFTWARE WILL BE CORRECTED, OR THAT THE APPLE
 * SOFTWARE WILL BE COMPATIBLE WITH FUTURE APPLE PRODUCTS, SOFTWARE OR SERVICES. NO ORAL
 * OR WRITTEN INFORMATION OR ADVICE GIVEN BY APPLE OR AN APPLE AUTHORIZED REPRESENTATIVE
 * WILL CREATE A WARRANTY. 
 * 
 * 3.	IN NO EVENT SHALL APPLE BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ARISING
 * IN ANY WAY OUT OF THE USE, REPRODUCTION, COMPILATION OR OPERATION OF THE APPLE
 * SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING
 * NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * 4.	This Agreement is effective until terminated. Your rights under this Agreement will
 * terminate automatically without notice from Apple if you fail to comply with any term(s)
 * of this Agreement.  Upon termination, you agree to cease all use of the Apple Software
 * and destroy all copies, full or partial, of the Apple Software. This Agreement will be
 * governed and construed in accordance with the laws of the State of California, without
 * regard to its choice of law rules.
 * 
 * You may report security issues about Apple products to product-security@apple.com,
 * as described here:  https://www.apple.com/support/security/.  Non-security bugs and
 * enhancement requests can be made via https://bugreport.apple.com as described
 * here: https://developer.apple.com/bug-reporting/
 *
 * EA1350 
 * 10/5/15
 */


/* Autogenerated file - Use scheme ccdh_gen_gp */
#include <corecrypto/ccdh_priv.h>
#include <corecrypto/ccdh_gp.h>

static const ccdh_gp_decl_static(1024) _ccdh_gp_rfc5114_MODP_1024_160 =
{
    .zp = {
        .n = ccn_nof(1024),
        .options = 0,
        .mod_prime = cczp_mod
    },
    .p = {
        /* prime */
        CCN64_C(df,1f,b2,bc,2e,4a,43,71),CCN64_C(e6,8c,fd,a7,6d,4d,a7,08),
        CCN64_C(45,bf,37,df,36,5c,1a,65),CCN64_C(a1,51,af,5f,0d,c8,b4,bd),
        CCN64_C(fa,a3,1a,4f,f5,5b,cc,c0),CCN64_C(4e,ff,d6,fa,e5,64,47,38),
        CCN64_C(98,48,8e,9c,21,9a,73,72),CCN64_C(ac,cb,dd,7d,90,c4,bd,70),
        CCN64_C(24,97,5c,3c,d4,9b,83,bf),CCN64_C(13,ec,b4,ae,a9,06,11,23),
        CCN64_C(98,38,ef,1e,2e,e6,52,c0),CCN64_C(60,73,e2,86,75,a2,3d,18),
        CCN64_C(9a,6a,9d,ca,52,d2,3b,61),CCN64_C(52,c9,9f,bc,fb,06,a3,c6),
        CCN64_C(de,92,de,5e,ae,5d,54,ec),CCN64_C(b1,0b,8f,96,a0,80,e0,1d)
    },
    .recip = {
        /* recip */
        CCN64_C(88,07,72,e1,3d,f1,19,d7),CCN64_C(9a,8b,36,14,50,b0,07,41),
        CCN64_C(99,7f,9f,25,1c,79,c8,e3),CCN64_C(52,cb,c8,75,93,f0,0a,83),
        CCN64_C(78,c5,61,ff,f2,e2,89,bc),CCN64_C(68,d6,94,b1,35,09,39,c6),
        CCN64_C(bb,77,00,dc,75,f9,e3,82),CCN64_C(51,98,a6,f2,d6,84,60,a3),
        CCN64_C(de,81,cc,5a,f3,b6,72,24),CCN64_C(02,b4,21,d0,77,f9,47,a6),
        CCN64_C(79,68,36,96,d1,6f,a7,d5),CCN64_C(af,3a,c9,0d,16,a5,e9,a4),
        CCN64_C(8a,a3,8c,db,d6,bd,09,83),CCN64_C(56,af,07,a7,b0,42,db,09),
        CCN64_C(cc,34,5c,d8,db,24,da,bc),CCN64_C(72,2a,5a,7a,6f,cd,55,9d),
        CCN8_C(01)
    },
    .g = {
        /* g */
        CCN64_C(85,5e,6e,eb,22,b3,b2,e5),CCN64_C(85,8f,4d,ce,f9,7c,2a,24),
        CCN64_C(2d,77,9d,59,18,d0,8b,c8),CCN64_C(d6,62,a4,d1,8e,73,af,a3),
        CCN64_C(1d,bf,0a,01,69,b6,a2,8a),CCN64_C(a6,a2,4c,08,7a,09,1f,53),
        CCN64_C(90,9d,0d,22,63,f8,0a,76),CCN64_C(d7,fb,d7,d3,b9,a9,2e,e1),
        CCN64_C(5e,91,54,7f,9e,27,49,f4),CCN64_C(16,02,17,b4,b0,1b,88,6a),
        CCN64_C(77,7e,69,0f,55,04,f2,13),CCN64_C(26,6f,ea,1e,5c,41,56,4b),
        CCN64_C(d6,40,6c,ff,14,26,6d,31),CCN64_C(f8,10,4d,d2,58,ac,50,7f),
        CCN64_C(67,65,a4,42,ef,b9,99,05),CCN64_C(a4,d1,cb,d5,c3,fd,34,12)
    },
    .q = {
        /* q */
        CCN64_C(64,b7,cb,9d,49,46,23,53),CCN64_C(81,a8,df,27,8a,ba,4e,7d),
        CCN64_C(00,00,00,00,f5,18,aa,87),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .l = 0,
};

ccdh_const_gp_t ccdh_gp_rfc5114_MODP_1024_160(void)
{
    return (ccdh_const_gp_t)(cczp_const_t)(const cc_unit *)&_ccdh_gp_rfc5114_MODP_1024_160;
}

