/*
 * Copyright (c) 2011,2015 Apple Inc. All rights reserved.
 * 
 * corecrypto Internal Use License Agreement
 * 
 * IMPORTANT:  This Apple corecrypto software is supplied to you by Apple Inc. ("Apple")
 * in consideration of your agreement to the following terms, and your download or use
 * of this Apple software constitutes acceptance of these terms.  If you do not agree
 * with these terms, please do not download or use this Apple software.
 * 
 * 1.	As used in this Agreement, the term "Apple Software" collectively means and
 * includes all of the Apple corecrypto materials provided by Apple here, including
 * but not limited to the Apple corecrypto software, frameworks, libraries, documentation
 * and other Apple-created materials. In consideration of your agreement to abide by the
 * following terms, conditioned upon your compliance with these terms and subject to
 * these terms, Apple grants you, for a period of ninety (90) days from the date you
 * download the Apple Software, a limited, non-exclusive, non-sublicensable license
 * under Apple’s copyrights in the Apple Software to make a reasonable number of copies
 * of, compile, and run the Apple Software internally within your organization only on
 * devices and computers you own or control, for the sole purpose of verifying the
 * security characteristics and correct functioning of the Apple Software; provided
 * that you must retain this notice and the following text and disclaimers in all
 * copies of the Apple Software that you make. You may not, directly or indirectly,
 * redistribute the Apple Software or any portions thereof. The Apple Software is only
 * licensed and intended for use as expressly stated above and may not be used for other
 * purposes or in other contexts without Apple's prior written permission.  Except as
 * expressly stated in this notice, no other rights or licenses, express or implied, are
 * granted by Apple herein.
 * 
 * 2.	The Apple Software is provided by Apple on an "AS IS" basis.  APPLE MAKES NO
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES
 * OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, REGARDING
 * THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS,
 * SYSTEMS, OR SERVICES. APPLE DOES NOT WARRANT THAT THE APPLE SOFTWARE WILL MEET YOUR
 * REQUIREMENTS, THAT THE OPERATION OF THE APPLE SOFTWARE WILL BE UNINTERRUPTED OR
 * ERROR-FREE, THAT DEFECTS IN THE APPLE SOFTWARE WILL BE CORRECTED, OR THAT THE APPLE
 * SOFTWARE WILL BE COMPATIBLE WITH FUTURE APPLE PRODUCTS, SOFTWARE OR SERVICES. NO ORAL
 * OR WRITTEN INFORMATION OR ADVICE GIVEN BY APPLE OR AN APPLE AUTHORIZED REPRESENTATIVE
 * WILL CREATE A WARRANTY. 
 * 
 * 3.	IN NO EVENT SHALL APPLE BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ARISING
 * IN ANY WAY OUT OF THE USE, REPRODUCTION, COMPILATION OR OPERATION OF THE APPLE
 * SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING
 * NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * 4.	This Agreement is effective until terminated. Your rights under this Agreement will
 * terminate automatically without notice from Apple if you fail to comply with any term(s)
 * of this Agreement.  Upon termination, you agree to cease all use of the Apple Software
 * and destroy all copies, full or partial, of the Apple Software. This Agreement will be
 * governed and construed in accordance with the laws of the State of California, without
 * regard to its choice of law rules.
 * 
 * You may report security issues about Apple products to product-security@apple.com,
 * as described here:  https://www.apple.com/support/security/.  Non-security bugs and
 * enhancement requests can be made via https://bugreport.apple.com as described
 * here: https://developer.apple.com/bug-reporting/
 *
 * EA1350 
 * 10/5/15
 */


/* Autogenerated file - Use scheme ccdh_gen_gp */
#include <corecrypto/ccdh_priv.h>
#include <corecrypto/ccdh_gp.h>

static const ccdh_gp_decl_static(2048) _ccdh_gp_rfc5114_MODP_2048_224 =
{
    .zp = {
        .n = ccn_nof(2048),
        .options = 0,
        .mod_prime = cczp_mod
    },
    .p = {
        /* prime */
        CCN64_C(0a,c4,df,fe,0c,10,e6,4f),CCN64_C(cf,9d,e5,38,4e,71,b8,1c),
        CCN64_C(7e,f3,63,e2,ff,a3,1f,71),CCN64_C(e3,fb,73,c1,6b,8e,75,b9),
        CCN64_C(c9,b5,3d,cf,4b,a8,0a,29),CCN64_C(23,f1,0b,0e,16,e7,97,63),
        CCN64_C(c5,21,72,e4,13,04,2e,9b),CCN64_C(be,60,e6,9c,c9,28,b2,b9),
        CCN64_C(80,cd,86,a1,b9,e5,87,e8),CCN64_C(31,5d,75,e1,98,c6,41,a4),
        CCN64_C(cd,f9,3a,cc,44,32,83,87),CCN64_C(15,98,7d,9a,dc,0a,48,6d),
        CCN64_C(73,10,f7,12,1f,d5,a0,74),CCN64_C(27,82,73,c7,de,31,ef,dc),
        CCN64_C(16,02,e7,14,41,5d,93,30),CCN64_C(81,28,61,30,bc,89,85,db),
        CCN64_C(b3,bf,8a,31,70,91,88,36),CCN64_C(6a,00,e0,a0,b9,c4,97,08),
        CCN64_C(c6,ba,0b,2c,8b,bc,27,be),CCN64_C(c9,f9,8d,11,ed,34,db,f6),
        CCN64_C(7a,d5,b7,d0,b6,c1,22,07),CCN64_C(d9,1e,8f,ef,55,b7,39,4b),
        CCN64_C(90,37,c9,ed,ef,da,4d,f8),CCN64_C(6d,3f,81,52,ad,6a,c2,12),
        CCN64_C(1d,e6,b8,5a,12,74,a0,a6),CCN64_C(eb,3d,68,8a,30,9c,18,0e),
        CCN64_C(af,9a,3c,40,7b,a1,df,15),CCN64_C(e6,fa,14,1d,f9,5a,56,db),
        CCN64_C(b5,4b,15,97,b6,1d,0a,75),CCN64_C(a2,0d,64,e5,68,3b,9f,d1),
        CCN64_C(d6,60,fa,a7,95,59,c5,1f),CCN64_C(ad,10,7e,1e,91,23,a9,d0)
    },
    .recip = {
        /* recip */
        CCN64_C(3d,51,f7,b8,55,91,b3,db),CCN64_C(9b,f6,66,74,06,67,e8,37),
        CCN64_C(44,24,b0,06,26,96,ed,69),CCN64_C(7d,49,27,39,f7,d9,1b,62),
        CCN64_C(3c,ab,70,c6,6b,9f,b3,03),CCN64_C(41,8d,5e,d4,a8,59,4d,7d),
        CCN64_C(5f,0c,71,2a,45,c3,6b,7f),CCN64_C(c7,60,f9,64,0a,e9,37,de),
        CCN64_C(19,dd,f3,6b,2b,c7,2e,c4),CCN64_C(fc,61,48,9c,01,a7,d2,d7),
        CCN64_C(84,58,53,5a,e7,98,95,1b),CCN64_C(90,c1,13,ed,5c,7f,c0,a7),
        CCN64_C(0b,24,c6,44,e4,cc,41,d2),CCN64_C(0f,bd,8a,bc,2d,a8,f6,83),
        CCN64_C(ae,ec,68,54,3b,e4,40,a6),CCN64_C(ed,23,6f,80,0b,04,31,1e),
        CCN64_C(6a,9b,20,06,50,64,fd,86),CCN64_C(65,10,ee,4e,98,e6,57,61),
        CCN64_C(f3,dd,05,1c,be,41,e2,a7),CCN64_C(57,a4,28,de,2a,59,2b,2a),
        CCN64_C(49,20,39,c4,17,a9,e3,b2),CCN64_C(4d,be,03,f2,3b,ba,71,17),
        CCN64_C(7d,1d,0d,74,96,8d,c3,31),CCN64_C(a3,c2,1a,34,c3,96,80,f3),
        CCN64_C(23,f7,48,2e,0c,54,66,c1),CCN64_C(23,07,b0,d9,a9,9b,fb,59),
        CCN64_C(18,c1,c7,37,f1,2a,14,d8),CCN64_C(55,8f,81,81,49,1e,69,0b),
        CCN64_C(80,8c,60,92,5c,3d,f8,7e),CCN64_C(74,96,af,0b,57,7a,fc,3d),
        CCN64_C(d5,5d,82,21,d6,e3,c6,f8),CCN64_C(7a,ae,06,c1,6b,48,7b,18),
        CCN8_C(01)
    },
    .g = {
        /* g */
        CCN64_C(84,b8,90,d3,19,1f,2b,fa),CCN64_C(81,bc,08,7f,2a,70,65,b3),
        CCN64_C(19,c4,18,e1,f6,ec,01,79),CCN64_C(7b,5a,0f,1c,71,cf,ff,4c),
        CCN64_C(ed,fe,72,fe,9b,6a,a4,bd),CCN64_C(81,e1,bc,fe,94,b3,02,69),
        CCN64_C(56,6a,fb,b4,8d,6c,01,91),CCN64_C(b5,39,cc,e3,40,9d,13,cd),
        CCN64_C(6a,a2,1e,7f,5f,2f,f3,81),CCN64_C(d9,e2,63,e4,77,05,89,ef),
        CCN64_C(10,e1,83,ed,d1,99,63,dd),CCN64_C(b7,0a,81,37,15,0b,8e,eb),
        CCN64_C(05,1a,e3,d4,28,c8,f8,ac),CCN64_C(bb,77,a8,6f,0c,1a,b1,5b),
        CCN64_C(6e,30,25,e3,16,a3,30,ef),CCN64_C(19,52,9a,45,d6,f8,34,56),
        CCN64_C(f1,80,eb,34,11,8e,98,d1),CCN64_C(b5,f6,c6,b2,50,71,7c,be),
        CCN64_C(09,93,9d,54,da,74,60,cd),CCN64_C(e2,47,15,04,22,ea,1e,d4),
        CCN64_C(b8,a7,62,d0,52,1b,c9,8a),CCN64_C(f4,d0,27,27,5a,c1,34,8b),
        CCN64_C(c1,76,69,10,19,99,02,4a),CCN64_C(be,5e,90,01,a8,d6,6a,d7),
        CCN64_C(c5,7d,b1,7c,62,0a,86,52),CCN64_C(ab,73,9d,77,00,c2,9f,52),
        CCN64_C(dd,92,1f,01,a7,0c,4a,fa),CCN64_C(a6,82,4a,4e,10,b9,a6,f0),
        CCN64_C(74,86,6a,08,cf,e4,ff,e3),CCN64_C(6c,de,be,7b,89,99,8c,af),
        CCN64_C(9d,f3,0b,5c,8f,fd,ac,50),CCN64_C(ac,40,32,ef,4f,2d,9a,e3)
    },
    .q = {
        /* q */
        CCN64_C(bf,38,9a,99,b3,63,71,eb),CCN64_C(1f,80,53,5a,47,38,ce,bc),
        CCN64_C(c5,8d,93,fe,99,71,77,10),CCN64_C(00,00,00,00,80,1c,0d,34),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .l = 0,
};

ccdh_const_gp_t ccdh_gp_rfc5114_MODP_2048_224(void)
{
    return (ccdh_const_gp_t)(cczp_const_t)(const cc_unit *)&_ccdh_gp_rfc5114_MODP_2048_224;
}

