Document: eid-mw
Title: Debian eid-mw Manual
Author: <insert document author here>
Abstract: This manual describes what eid-mw is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/eid-mw/eid-mw.sgml.gz

Format: postscript
Files: /usr/share/doc/eid-mw/eid-mw.ps.gz

Format: text
Files: /usr/share/doc/eid-mw/eid-mw.text.gz

Format: HTML
Index: /usr/share/doc/eid-mw/html/index.html
Files: /usr/share/doc/eid-mw/html/*.html
