#!/bin/sh

if [ -d debian/tmp/usr/lib/eid-mw ]; then
	echo usr/lib/eid-mw
	echo usr/share/locale/*/LC_MESSAGES/dialogs-beid.mo
fi
cat <<EOF
usr/bin/about-eid-mw
usr/share/locale/*/LC_MESSAGES/about-eid-mw.mo
usr/lib/mozilla/pkcs11-modules/beidpkcs11.json
usr/lib/mozilla/pkcs11-modules/beidpkcs11_alt.json
usr/lib/mozilla/managed-storage/belgiumeid@eid.belgium.be.json
usr/bin/beid-update-nssdb
etc/xdg/autostart
EOF
pkg-config --variable=p11_system_config_modules p11-kit-1 | sed -e 's,^/,,'
