Import('env')
myenv = env.Copy()
myenv.Append(CPPPATH='../include', LIBS=['beidlibopensc'], LIBPATH=['../libopensc'])
myenv.Append(CCFLAGS=' -DHAVE_OPENSSL')
obj = myenv.genobj('shlib', myenv)
obj.src = Split("""
debug.c
framework-pkcs15init.c
mechanism.c
openssl.c
pkcs11-global.c
pkcs11-session.c
secretkey.c
framework-pkcs15.c
libpkcs11.c
misc.c
pkcs11-display.c
pkcs11-object.c
slot.c
../scrandom/scrandom.c
""")
obj.target='libbeidpkcs11'
obj.vnum='2.1.0'
obj.execute()
prefix = env['PREFIX']
libdir = env['LIBDIR']
env.Alias('install', env.Install(libdir, obj.target + '.so.' + obj.vnum))
env.Alias('install', env.Install(libdir, obj.target + '.so'))
