include ../../../_Builds/archs.mac     # for $(EXTRA_DEF) and $(ARCHS)

TARGET = ../../../_Binaries/libjpcsc.jnilib

OBJS = jpcsc.o

CFLAGS = -DDARWIN -Wall -Wno-pointer-sign $(EXTRA_DEF) $(ARCHS)
INCLUDE = -I/System/Library/Frameworks/PCSC.framework/Headers/ \
	-I/System/Library/Frameworks/JavaVM.framework/Headers/
LIBS = -lpthread -Wl,-framework -Wl,PCSC
LFLAGS = -fPIC -headerpad_max_install_names -single_module -dynamiclib -compatibility_version 1.0.0

all: $(TARGET)

clean:
	- rm $(OBJS) $(TARGET)

$(TARGET): $(OBJS)
	gcc $(LFLAGS) -o $(TARGET) $(OBJS) $(LIBS)	

%.o: %.c *.h
	gcc -c $(INCLUDE) $(CFLAGS) $< -o $@
