Import('env')
myenv = env.Copy()
obj=myenv.genobj('shlib', myenv)
obj.target='libbeidpcsclite'
obj.src=Split("""
ServerPoll.cpp
winscarp.cpp
""")
#obj.cxxflags='-D_DEBUGLOGTIME -D_DEBUGLOG'
obj.includes='../eidlib'
obj.vnum='2.7.1'
obj.libs='beidcomm beidcommon'
obj.libpaths='../beidcommlib ../beidcommon'
obj.execute()
libdir = env['LIBDIR']
env.Alias('install', env.Install(libdir, obj.target + '.so.' + obj.vnum) )
env.Alias('install', env.Install(libdir, obj.target + '.so') )

