#!/bin/bash

#prior to OS X 10.11, try to copy tokend to the /System folder (otherwise, the tokends in this folder get priority)
if [[ $(sw_vers -productVersion) == *10.10* || $(sw_vers -productVersion) == *10.9* || $(sw_vers -productVersion) == *10.8* || $(sw_vers -productVersion) == *10.7* ]]; then
	if test -e /System/Library/Security/tokend/BEID.tokend; then
		sudo rm -rf /System/Library/Security/tokend/BEID.tokend
	fi
	sudo cp -r /Library/Security/tokend/BEID.tokend /System/Library/Security/tokend/
fi

echo "postinstall BEIDtokenD succeeded"
