Import('env')
myenv = env.Copy()

#myenv.Tool('wx', toolpath=['../../admin'])
myenv.ParseConfig('wx-config --cppflags')
myenv.ParseConfig('wx-config --libs')

obj=myenv.genobj('program', myenv)
obj.target='beidgui'
obj.src=Split("""
Certif.cpp  
eidviewerApp.cpp
eidviewerFrame.cpp
eidviewerTypes.cpp
Pin.cpp
PrintOutData.cpp
Config.cpp
eidviewerNotebook.cpp
PrintOut.cpp
""")
obj.includes='../eidlib ../newpkcs11/src/include'
obj.libs='ssl beid beidlibopensc beidpcsclite beidcomm beidcommon'
obj.libpaths='../eidlib ../newpkcs11/src/libopensc ../winscarp ../beidcommlib ../beidcommon'
obj.execute()

prefix = env['PREFIX']
confdir = env['CONFDIR']
env.Alias('install', env.Install(prefix + '/bin', obj.target))
env.Alias('install', env.Install(prefix + '/share/locale', 'beidgui_nl.mo' ) )
env.Alias('install', env.Install(prefix + '/share/locale', 'beidgui_fr.mo' ) )
env.Alias('install', env.Install(prefix + '/share/locale', 'beidgui_de.mo' ) )
env.Alias('install', env.Install(confdir, 'beidgui.conf' ) )
certdir=prefix+'/share/beid/certs'
crldir=prefix+'/share/beid/crl'
env.Alias('install', env.Install(certdir, 'certs/beid-cert-belgiumrca.der'))
env.Alias('install', env.Install(certdir, 'certs/beid-cert-government2004.der'))
env.Alias('install', env.Install(certdir, 'certs/beid-cert-government2005.der'))
env.Alias('install', env.Install(certdir, 'certs/beid-cert-government.der'))
env.Alias('install', env.Command('', '', [Mkdir('crldir'), Chmod('crldir', 0777)]))
env.Alias('install', env.Install(prefix + '/bin', 'res/beidgui.png'))
env.Alias('install', env.Install(prefix + '/bin', 'beidgui.desktop'))
