#!/bin/bash
export PRE="$HOME/dist"

sudo rm -Rf $PRE/*
sudo mkdir $PRE/{lin64,lin32,osx64,osx32,win64,win32}

DIST_PREFIX=$PRE/lin64 ./build_linux64
DIST_PREFIX=$PRE/lin32 ./build_linux32
#DIST_PREFIX=$PRE/osx64 ./build_osx64
#DIST_PREFIX=$PRE/osx32 ./build_osx32
DIST_PREFIX=$PRE/win64 ./build_windows64
DIST_PREFIX=$PRE/win32 ./build_windows32
