#!/bin/bash
make clean
./configure CFLAGS="-arch i386" LDFLAGS="-arch i386" CXXFLAGS="-arch i386" --prefix /Library/Frameworks/BeId.framework/Versions/4.0.0/
make
make install DESTDIR="${HOME}/eid-mw/dmg/src/dist/osx32/"

