include ../_Builds/archs.mac

OBJECTS = main.o pcscerr2string.o utils.o

TARGET = ../_Binaries/pcsctool

CPPFLAGS = -Wall -O3 #$(ARCHS) -fmessage-length=0
INCLUDE = -I. -I/System/Library/Frameworks/PCSC.framework/Headers

all: $(TARGET)

clean:
	- rm *.o $(TARGET)

$(TARGET): $(OBJECTS)
	g++ $(OBJECTS) -Wl,-framework -Wl,PCSC -o $(TARGET)

%.o: %.cpp *.h
	g++ -c $(INCLUDE) $(CPPFLAGS) $< -o $@
