include ../_Builds/archs.mac

OBJECTS = Logger.o controlFileAccess.o virtualCardAccess.o Mutex.o util.o xml.o

TARGET = libeidtestinfra.a

CPPFLAGS = -Wall -O3 #$(ARCHS) -fmessage-length=0

all: $(TARGET)

clean:
	- rm *.o $(TARGET)

$(TARGET): $(OBJECTS)
	ar -r $(TARGET) $(OBJECTS)

%.o: %.cpp *.h
	g++ -c $(CPPFLAGS) $< -o $@
