Import('env')
myenv = env.Copy()
obj=myenv.genobj('program', myenv)
obj.target='beidpcscd'
obj.src=Split("""
maindialog.ui

ApplicationManager.cpp
CardChangeMonitor.cpp
main.cpp
PCSCManager.cpp
ReaderObject.cpp
SCardHandler.cpp
TransactionStack.cpp
ApplicationObject.cpp
maindialogimpl.cpp
ReaderState.cpp
StdAfx.cpp
""")
# if _PRIVACY_REMOTE_SVC defined then acting as remote service instead of a privacy filter
#obj.cxxflags='-D_DEBUGLOG'
obj.libs='ssl beidlibopensc beidpcsclite beidcomm beidcommon'
obj.libpaths='../eidlib ../newpkcs11/src/libopensc ../winscarp ../beidcommlib ../beidcommon'
obj.includes='../eidlib'
obj.execute()

prefix = env['PREFIX']
initscript = 'belgium.be-beidpcscd'
env.Alias('install', env.Install(prefix + '/bin', obj.target))
env.Alias('install', env.Install('/etc/init.d', initscript))
