//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIDViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIDViewer.Resources.ApplicationStringResources", typeof(ApplicationStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        public static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card/PIN.
        /// </summary>
        public static string CARD {
            get {
                return ResourceManager.GetString("CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string CERTIFICATES {
            get {
                return ResourceManager.GetString("CERTIFICATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/Images/coat_of_arms_en.jpg.
        /// </summary>
        public static string coat_of_arms_jpg_location {
            get {
                return ResourceManager.GetString("coat_of_arms_jpg_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string fileMenuQuitItem {
            get {
                return ResourceManager.GetString("fileMenuQuitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string fileMenuTitle {
            get {
                return ResourceManager.GetString("fileMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string helpMenuTitle {
            get {
                return ResourceManager.GetString("helpMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string IDENTITY {
            get {
                return ResourceManager.GetString("IDENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string languageMenuTitle {
            get {
                return ResourceManager.GetString("languageMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LOG {
            get {
                return ResourceManager.GetString("LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of the eID Viewer has been found, would you like to download it?.
        /// </summary>
        public static string newVersionDownload {
            get {
                return ResourceManager.GetString("newVersionDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version eID Viewer.
        /// </summary>
        public static string newVersionDownloadTitle {
            get {
                return ResourceManager.GetString("newVersionDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PIN was changed correctly..
        /// </summary>
        public static string pinChangedOKDialogMessage {
            get {
                return ResourceManager.GetString("pinChangedOKDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN changed.
        /// </summary>
        public static string pinChangedOKDialogTitle {
            get {
                return ResourceManager.GetString("pinChangedOKDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PIN was validated correctly..
        /// </summary>
        public static string pinVerifiedOKDialogMessage {
            get {
                return ResourceManager.GetString("pinVerifiedOKDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN validated OK.
        /// </summary>
        public static string pinVerifiedOKDialogTitle {
            get {
                return ResourceManager.GetString("pinVerifiedOKDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print...
        /// </summary>
        public static string printButtonTitle {
            get {
                return ResourceManager.GetString("printButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed by:.
        /// </summary>
        public static string printedBy {
            get {
                return ResourceManager.GetString("printedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed:.
        /// </summary>
        public static string printedDateLabel {
            get {
                return ResourceManager.GetString("printedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log Tab.
        /// </summary>
        public static string showLogTab {
            get {
                return ResourceManager.GetString("showLogTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online update check failed, please check log for further details.
        /// </summary>
        public static string updateCheckError {
            get {
                return ResourceManager.GetString("updateCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online update check failed.
        /// </summary>
        public static string updateCheckErrorTitle {
            get {
                return ResourceManager.GetString("updateCheckErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version of the eID Viewer has already been installed.
        /// </summary>
        public static string VersionUpToDate {
            get {
                return ResourceManager.GetString("VersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eID Viewer is up to date.
        /// </summary>
        public static string VersionUpToDateTitle {
            get {
                return ResourceManager.GetString("VersionUpToDateTitle", resourceCulture);
            }
        }
    }
}
