//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIDViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityTabStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityTabStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIDViewer.Resources.IdentityTabStringResources", typeof(IdentityTabStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brexit mentions:.
        /// </summary>
        public static string Brexit_mentions {
            get {
                return ResourceManager.GetString("Brexit_mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions:.
        /// </summary>
        public static string CardA_mentions {
            get {
                return ResourceManager.GetString("CardA_mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        public static string DateOfBirthLabel {
            get {
                return ResourceManager.GetString("DateOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate:.
        /// </summary>
        public static string DuplicateLabel {
            get {
                return ResourceManager.GetString("DuplicateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer&apos;s VAT/
        ///CBE number (1):.
        /// </summary>
        public static string EmployersVATNumber1Label {
            get {
                return ResourceManager.GetString("EmployersVATNumber1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer&apos;s VAT/
        ///CBE number (2):.
        /// </summary>
        public static string EmployersVATNumber2Label {
            get {
                return ResourceManager.GetString("EmployersVATNumber2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string genderFemale {
            get {
                return ResourceManager.GetString("genderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string genderMale {
            get {
                return ResourceManager.GetString("genderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given names:.
        /// </summary>
        public static string GivenNamesLabel {
            get {
                return ResourceManager.GetString("GivenNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family member.
        /// </summary>
        public static string MemberLabel {
            get {
                return ResourceManager.GetString("MemberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality:.
        /// </summary>
        public static string MunicipalityLabel {
            get {
                return ResourceManager.GetString("MunicipalityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality:.
        /// </summary>
        public static string NationalityLabel {
            get {
                return ResourceManager.GetString("NationalityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National number:.
        /// </summary>
        public static string NationalNumberLabel {
            get {
                return ResourceManager.GetString("NationalNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth:.
        /// </summary>
        public static string PlaceOfBirthLabel {
            get {
                return ResourceManager.GetString("PlaceOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code:.
        /// </summary>
        public static string PostalCodeLabel {
            get {
                return ResourceManager.GetString("PostalCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and country
        ///of international protection:.
        /// </summary>
        public static string ProtectionLabel {
            get {
                return ResourceManager.GetString("ProtectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional file number:.
        /// </summary>
        public static string RegionalFileNumberLabel {
            get {
                return ResourceManager.GetString("RegionalFileNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex:.
        /// </summary>
        public static string SexLabel {
            get {
                return ResourceManager.GetString("SexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously holder of European Blue Card.
        /// </summary>
        public static string special_organisation_former_blue_card {
            get {
                return ResourceManager.GetString("special_organisation_former_blue_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATO.
        /// </summary>
        public static string special_organisation_nato {
            get {
                return ResourceManager.GetString("special_organisation_nato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher.
        /// </summary>
        public static string special_organisation_researcher {
            get {
                return ResourceManager.GetString("special_organisation_researcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHAPE.
        /// </summary>
        public static string special_organisation_shape {
            get {
                return ResourceManager.GetString("special_organisation_shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Nonage.
        /// </summary>
        public static string special_status_extended_minority {
            get {
                return ResourceManager.GetString("special_status_extended_minority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Cane.
        /// </summary>
        public static string special_status_white_cane {
            get {
                return ResourceManager.GetString("special_status_white_cane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cane.
        /// </summary>
        public static string special_status_yellow_cane {
            get {
                return ResourceManager.GetString("special_status_yellow_cane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special organisation:.
        /// </summary>
        public static string SpecialOrganisationLabel {
            get {
                return ResourceManager.GetString("SpecialOrganisationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special status:.
        /// </summary>
        public static string SpecialStatusLabel {
            get {
                return ResourceManager.GetString("SpecialStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string StreetLabel {
            get {
                return ResourceManager.GetString("StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTITY CARD.
        /// </summary>
        public static string type_BELGIAN_CITIZEN {
            get {
                return ResourceManager.GetString("type_BELGIAN_CITIZEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOTSTRAP CARD.
        /// </summary>
        public static string type_BOOTSTRAP_CARD {
            get {
                return ResourceManager.GetString("type_BOOTSTRAP_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. European Blue Card.
        /// </summary>
        public static string type_EUROPEAN_BLUE_CARD_H {
            get {
                return ResourceManager.GetString("type_EUROPEAN_BLUE_CARD_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of registration in the Aliens’ Register – Temporary residence.
        /// </summary>
        public static string type_FOREIGNER_A {
            get {
                return ResourceManager.GetString("type_FOREIGNER_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of registration in the Aliens’ Register.
        /// </summary>
        public static string type_FOREIGNER_B {
            get {
                return ResourceManager.GetString("type_FOREIGNER_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card for Aliens.
        /// </summary>
        public static string type_FOREIGNER_C {
            get {
                return ResourceManager.GetString("type_FOREIGNER_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-term EU Resident.
        /// </summary>
        public static string type_FOREIGNER_D {
            get {
                return ResourceManager.GetString("type_FOREIGNER_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Residence) permit of EU Citizen – Certificate of Registration.
        /// </summary>
        public static string type_FOREIGNER_E {
            get {
                return ResourceManager.GetString("type_FOREIGNER_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document in evidence of durable residence of an EU Citizen.
        /// </summary>
        public static string type_FOREIGNER_E_PLUS {
            get {
                return ResourceManager.GetString("type_FOREIGNER_E_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit for non-EU family members of an EU Citizen or Belgian national.
        /// </summary>
        public static string type_FOREIGNER_F {
            get {
                return ResourceManager.GetString("type_FOREIGNER_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durable residence permit of a family member of an EU Citizen.
        /// </summary>
        public static string type_FOREIGNER_F_PLUS {
            get {
                return ResourceManager.GetString("type_FOREIGNER_F_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitation Card.
        /// </summary>
        public static string type_HABILITATION_CARD {
            get {
                return ResourceManager.GetString("type_HABILITATION_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIDS CARD.
        /// </summary>
        public static string type_KIDS_CARD {
            get {
                return ResourceManager.GetString("type_KIDS_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the labour market:.
        /// </summary>
        public static string WorkPermitMentionLabel {
            get {
                return ResourceManager.GetString("WorkPermitMentionLabel", resourceCulture);
            }
        }
    }
}
