Vagrant.configure("2") do |config|
  grouphash = {
      "debuntu" => [ "debian9", "debian10", "ubuntu1804", "ubuntu2004", "ubuntu2010" ],
      "debian" => [ "debian9", "debian10" ],
      "ubuntu" => [ "ubuntu1804", "ubuntu2004", "ubuntu2010" ],
      "fedora" => [ "fedora32", "fedora33" ],
      "centos" => [ "centos7", "centos8" ],
      "suse" => [ "opensuse15" ],
    }
  genericmachines = [ "debian9", "debian10",
	"ubuntu1804", "ubuntu2004", "ubuntu2010", "fedora32",
	"fedora33", "opensuse15", "centos7", "centos8" ]
  genericmachines.each do |machine|
    config.vm.define machine do |config|
      config.vm.box = "generic/#{machine}"
    end
  end

  config.vm.provider :virtualbox do |vb|
     vb.memory = "2048"
     vb.customize ['modifyvm', :id, '--usb', 'on']
     vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'ACR38 USB Reader', '--vendorid', '0x072f', '--productid', '0x9000']
  end

# config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "public_network"

  config.vm.provision :file, source: "./eid-archive_2020.4_all.deb", destination: "eid-archive.deb"
  config.vm.provision :file, source: "./google-chrome-stable.deb", destination: "google-chrome-stable.deb"
  config.vm.provision :file, source: "./eid-archive-fedora-2016-2.noarch.rpm", destination: "eid-archive-fedora.rpm"
  config.vm.provision :file, source: "./eid-archive-suse-2016-2.noarch.rpm", destination: "eid-archive-suse.rpm"
  config.vm.provision :file, source: "./eid-archive-el-2016-2.noarch.rpm", destination: "eid-archive-el.rpm"
  config.vm.provision :file, source: "./google-chrome-stable.rpm", destination: "google-chrome-stable.rpm"
  config.vm.provision :file, source: "./eid-playbook.yml", destination: "eid-playbook.yml"

  config.vm.provision :ansible_local do |ansible|
    ansible.install = true
    ansible.install_mode = :pip
    ansible.become = true
    ansible.groups = grouphash
    ansible.playbook = "eid-playbook.yml"
    ansible.provisioning_path = "/home/vagrant"
  end
end
