/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BelgianEidViewer.java
 *
 * Created on Nov 18, 2010, 2:25:04 PM
 */
package be.fedict.eidviewer.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ResourceBundle;

import be.fedict.eid.applet.DiagnosticTests;
import be.fedict.eid.applet.Messages;
import be.fedict.eid.applet.Messages.MESSAGE_ID;
import be.fedict.eid.applet.Status;
import be.fedict.eid.applet.View;
import be.fedict.eidviewer.lib.Eid;
import be.fedict.eidviewer.lib.EidFactory;
import java.awt.Component;
import java.awt.Toolkit;
import java.util.EnumMap;
import java.util.Locale;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
/**
 *
 * @author frank
 */
public class BelgianEidViewer extends javax.swing.JFrame implements View, Observer
{
    /** Creates new form BelgianEidViewer */

    private static final String EXTENSION_PNG = ".png";
    private static final String ICONS = "resources/icons/";
    private Messages mMessages;
    private Eid mEid;
    private EidController mEidController;
    private IdentityPanel mIdentityPanel;
    private CardPanel mCardPanel;
    private EnumMap<EidController.STATE, ImageIcon> mCardStatusIcons;

    public BelgianEidViewer()
    {
        Locale.setDefault(new Locale("nl", "BE"));
        initComponents();
        initPanels();
        initIcons();
        mMessages = new Messages(Locale.getDefault());
    }

    private void init()
    {
        mEid = EidFactory.getEidImpl(this, mMessages);
        mEidController = new EidController(mEid);
        mEidController.addObserver(mIdentityPanel);
        mEidController.addObserver(mCardPanel);
        mEidController.addObserver(this);
        mEidController.start();
        setVisible(true);
    }

    public void update(Observable o, Object o1)
    {
        EidController controller = (EidController) o;

        System.err.println("STATE [" + controller.getState().getState() + "]");

        statusIcon.setIcon(mCardStatusIcons.get(controller.getState()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new JTabbedPane();
        statusPanel = new JPanel();
        statusIcon = new JLabel();
        statusText = new JLabel();
        menuBar = new JMenuBar();
        fileMenu = new JMenu();
        fileMenuQuitItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(640, 480));

        tabPanel.setName("tabPanel"); // NOI18N
        getContentPane().add(tabPanel, BorderLayout.CENTER);

        statusPanel.setName("statusPanel"); // NOI18N
        statusPanel.setLayout(new BorderLayout());

        statusIcon.setHorizontalAlignment(SwingConstants.CENTER);
        statusIcon.setMaximumSize(new Dimension(72, 72));
        statusIcon.setMinimumSize(new Dimension(72, 72));
        statusIcon.setName("statusIcon"); // NOI18N
        statusIcon.setPreferredSize(new Dimension(72, 72));
        statusPanel.add(statusIcon, BorderLayout.EAST);

        statusText.setHorizontalAlignment(SwingConstants.RIGHT);
        ResourceBundle bundle = ResourceBundle.getBundle("be/fedict/eidviewer/gui/resources/BelgianEidViewer"); // NOI18N
        statusText.setText(bundle.getString("BelgianEidViewer.statusText.text")); // NOI18N
        statusText.setName("statusText"); // NOI18N
        statusPanel.add(statusText, BorderLayout.CENTER);

        getContentPane().add(statusPanel, BorderLayout.SOUTH);

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(bundle.getString("BelgianEidViewer.fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        fileMenuQuitItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Q, 0));
        fileMenuQuitItem.setText(bundle.getString("BelgianEidViewer.fileMenuQuitItem.text")); // NOI18N
        fileMenuQuitItem.setName("fileMenuQuitItem"); // NOI18N
        fileMenu.add(fileMenuQuitItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addDetailMessage(String detailMessage)
    {
        System.err.println(detailMessage);
    }

    public void setStatusMessage(Status status, MESSAGE_ID messageId)
    {
        String message = mMessages.getMessage(messageId);
        System.err.println(message);

        setStatusMessage(message);
    }

    private void setStatusMessage(final String message)
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                //idStatus.setText(message);
            }
        });
    }

    public boolean privacyQuestion(boolean includeAddress, boolean includePhoto, String identityDataUsage)
    {
        return true;
    }

    public Component getParentComponent()
    {
        return this.getParentComponent();
    }

    public void addTestResult(DiagnosticTests diagnosticTest, boolean success, String description)
    {
        System.err.println(description);
    }

    public void resetProgress(int max)
    {
        setProgress(0);
        System.err.println("|<<");
    }

    public void increaseProgress()
    {
        //setProgress(idProgressBar.getValue() + 1);
        System.err.println(">>");
    }

    private void setProgress(final int progress)
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                //idProgressBar.setValue(progress);
            }
        });
    }

    public void setProgressIndeterminate()
    {
        System.err.println("???");
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                //idProgressBar.setIndeterminate(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JMenu fileMenu;
    JMenuItem fileMenuQuitItem;
    JMenuBar menuBar;
    JLabel statusIcon;
    JPanel statusPanel;
    JLabel statusText;
    JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables


    private void initPanels()
    {
        ResourceBundle res  =java.util.ResourceBundle.getBundle("be/fedict/eidviewer/gui/resources/BelgianEidViewer");
        mIdentityPanel      = new IdentityPanel();
        mCardPanel          = new CardPanel();
        tabPanel.add(mIdentityPanel, res.getString("IDENTITY"));
        tabPanel.add(mCardPanel, res.getString("CARD"));

    }

    private void initIcons()
    {
        mCardStatusIcons = new EnumMap<EidController.STATE, ImageIcon>(EidController.STATE.class);
        mCardStatusIcons.put(EidController.STATE.NO_READERS, getIcon(EidController.STATE.NO_READERS.getState() + EXTENSION_PNG));
        mCardStatusIcons.put(EidController.STATE.NO_EID_PRESENT, getIcon(EidController.STATE.NO_EID_PRESENT.getState() + EXTENSION_PNG));
        mCardStatusIcons.put(EidController.STATE.EID_PRESENT, getIcon(EidController.STATE.EID_PRESENT.getState() + EXTENSION_PNG));
    }

    private ImageIcon getIcon(String name)
    {
        return new ImageIcon(Toolkit.getDefaultToolkit().getImage(BelgianEidViewer.class.getResource(ICONS + name)));
    }

        /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new BelgianEidViewer().init();
            }
        });
    }
}
