/*
 * Copyright (c) 2011,2012,2015 Apple Inc. All rights reserved.
 * 
 * corecrypto Internal Use License Agreement
 * 
 * IMPORTANT:  This Apple corecrypto software is supplied to you by Apple Inc. ("Apple")
 * in consideration of your agreement to the following terms, and your download or use
 * of this Apple software constitutes acceptance of these terms.  If you do not agree
 * with these terms, please do not download or use this Apple software.
 * 
 * 1.	As used in this Agreement, the term "Apple Software" collectively means and
 * includes all of the Apple corecrypto materials provided by Apple here, including
 * but not limited to the Apple corecrypto software, frameworks, libraries, documentation
 * and other Apple-created materials. In consideration of your agreement to abide by the
 * following terms, conditioned upon your compliance with these terms and subject to
 * these terms, Apple grants you, for a period of ninety (90) days from the date you
 * download the Apple Software, a limited, non-exclusive, non-sublicensable license
 * under Apple’s copyrights in the Apple Software to make a reasonable number of copies
 * of, compile, and run the Apple Software internally within your organization only on
 * devices and computers you own or control, for the sole purpose of verifying the
 * security characteristics and correct functioning of the Apple Software; provided
 * that you must retain this notice and the following text and disclaimers in all
 * copies of the Apple Software that you make. You may not, directly or indirectly,
 * redistribute the Apple Software or any portions thereof. The Apple Software is only
 * licensed and intended for use as expressly stated above and may not be used for other
 * purposes or in other contexts without Apple's prior written permission.  Except as
 * expressly stated in this notice, no other rights or licenses, express or implied, are
 * granted by Apple herein.
 * 
 * 2.	The Apple Software is provided by Apple on an "AS IS" basis.  APPLE MAKES NO
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES
 * OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, REGARDING
 * THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS,
 * SYSTEMS, OR SERVICES. APPLE DOES NOT WARRANT THAT THE APPLE SOFTWARE WILL MEET YOUR
 * REQUIREMENTS, THAT THE OPERATION OF THE APPLE SOFTWARE WILL BE UNINTERRUPTED OR
 * ERROR-FREE, THAT DEFECTS IN THE APPLE SOFTWARE WILL BE CORRECTED, OR THAT THE APPLE
 * SOFTWARE WILL BE COMPATIBLE WITH FUTURE APPLE PRODUCTS, SOFTWARE OR SERVICES. NO ORAL
 * OR WRITTEN INFORMATION OR ADVICE GIVEN BY APPLE OR AN APPLE AUTHORIZED REPRESENTATIVE
 * WILL CREATE A WARRANTY. 
 * 
 * 3.	IN NO EVENT SHALL APPLE BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ARISING
 * IN ANY WAY OUT OF THE USE, REPRODUCTION, COMPILATION OR OPERATION OF THE APPLE
 * SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING
 * NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * 4.	This Agreement is effective until terminated. Your rights under this Agreement will
 * terminate automatically without notice from Apple if you fail to comply with any term(s)
 * of this Agreement.  Upon termination, you agree to cease all use of the Apple Software
 * and destroy all copies, full or partial, of the Apple Software. This Agreement will be
 * governed and construed in accordance with the laws of the State of California, without
 * regard to its choice of law rules.
 * 
 * You may report security issues about Apple products to product-security@apple.com,
 * as described here:  https://www.apple.com/support/security/.  Non-security bugs and
 * enhancement requests can be made via https://bugreport.apple.com as described
 * here: https://developer.apple.com/bug-reporting/
 *
 * EA1350 
 * 10/5/15
 */


#include <corecrypto/cczp.h>
#include <corecrypto/ccn.h>
#include <stdbool.h>

/*
 * Table of small known primes, generated by makePrimes tool.
 */
static const uint16_t ccn_prime_table[] = {
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37,
    41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89,
    97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151,
    157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223,
    227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281,
    283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359,
    367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433,
    439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503,
    509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593,
    599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659,
    661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743,
    751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827,
    829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911,
    919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997,
    1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069,
    1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163,
    1171, 1181, 1187, 1193, 1201, 1213, 1217, 1223, 1229, 1231, 1237, 1249,
    1259, 1277, 1279, 1283, 1289, 1291, 1297, 1301, 1303, 1307, 1319, 1321,
    1327, 1361, 1367, 1373, 1381, 1399, 1409, 1423, 1427, 1429, 1433, 1439,
    1447, 1451, 1453, 1459, 1471, 1481, 1483, 1487, 1489, 1493, 1499, 1511,
    1523, 1531, 1543, 1549, 1553, 1559, 1567, 1571, 1579, 1583, 1597, 1601,
    1607, 1609, 1613, 1619
};

#define ccn_prime_table_n (sizeof(ccn_prime_table) / sizeof(*ccn_prime_table))

/*
 * composite = p[1] * p[2] * ... * p[119]
 */
#define composite_n  ccn_nof(928)

static const cc_unit composite[composite_n] = {
    CCN64_C(ae,ba,a3,91,75,03,b1,4f),
    CCN64_C(c1,5f,16,53,05,93,8f,16),
    CCN64_C(7c,63,91,a7,d6,dc,5e,8a),
    CCN64_C(6e,6d,c8,da,cd,00,89,f2),
    CCN64_C(60,e7,c1,03,32,59,1d,5f),
    CCN64_C(e0,e2,f2,64,b6,f9,81,59),
    CCN64_C(b6,af,87,d8,ce,5a,6f,7a),
    CCN64_C(36,24,27,e8,a4,58,26,6a),
    CCN64_C(48,a5,94,21,1e,30,57,2f),
    CCN64_C(ad,74,ea,76,e8,52,42,6a),
    CCN64_C(33,21,a1,de,b4,d6,43,df),
    CCN64_C(e6,e0,86,7c,43,58,ff,58),
    CCN64_C(83,70,32,65,1d,ee,e8,af),
    CCN64_C(d6,b8,87,dd,70,94,36,5d),
    CCN32_C(00,02,d2,59),
};

#define NUM_COMPONENT_PRIMES 120

/* Return 1 if p is the table of known primes, return 0 otherwise. */
static int ccn_is_known_prime(cc_size n, const cc_unit *p)
{
    if (ccn_bitlen(n, p) > 11)  // 1619 is 11 bits
        return 0;
    uint16_t v = (uint16_t)(p[0]);
    /* TODO: Consider a faster algorithm, like binary search here. */
    for (size_t i = 0; i < ccn_prime_table_n; ++i) {
        if (v == ccn_prime_table[i])
            return 1;
    }
    return 0;
}

/*
 * See if specified giant is a candidate for prime checking.
 */
enum ccn_prime_sieve_result {
    SIEVE_COMPOSITE,
    SIEVE_PRIME,
    SIEVE_CANDIDATE
};

static enum ccn_prime_sieve_result ccn_prime_sieve(cc_size n, const cc_unit *p) {
	/* dispose of trivial cases... */
	if (n == 0) {
		return SIEVE_COMPOSITE;		/* by convention here...technically it's
									 * neither prime nor composite.  */
	}

	if (!(p[0] & 1)) {
		/* even */
		if ((n == 1) && (p[0] == 2)) {
			/* okay okay, it's prime */
			return SIEVE_PRIME;
		}
		else {
			/* even, > 2, composite */
			return SIEVE_COMPOSITE;
		}
	}

	/* Quick check to see if p is a known prime in prime_table */
	if (ccn_is_known_prime(n, p)) {
		return SIEVE_PRIME;
	}

    /* Inline ccnm_gcd_is_one() function.
     TODO: Change interface to ccn_gcd to allow for 2 different sizes. */
    bool candidate;
    if (n > composite_n) {
        cc_unit gcd[n];
        ccn_zero(n - composite_n, gcd + composite_n);
        ccn_set(composite_n, gcd, composite);
        ccn_gcd(n, gcd, gcd, p);
        candidate = ccn_is_one(composite_n, gcd);
    } else if (n == composite_n) {
        cc_unit gcd[n];
        ccn_gcd(n, gcd, composite, p);
        candidate = ccn_is_one(composite_n, gcd);
    } else /* (n < composite_n) */ {
        cc_unit gcd[composite_n];
        ccn_zero(composite_n - n, gcd + n);
        ccn_set(n, gcd, p);
        ccn_gcd(composite_n, gcd, gcd, composite);
        candidate = ccn_is_one(composite_n, gcd);
    }

    if (candidate) {
		/* no factors in common - looks good */
		return SIEVE_CANDIDATE;
	} else {
		return SIEVE_COMPOSITE;
	}
}

/* When true - the normal case - ccn_rabin_miller() performs a preliminary
 sieve operation via ccn_prime_sieve. Disable for testing
 performance of ccn_rabin_miller() without the sieve. */
#define PERFORM_IMPLICIT_SIEVE	1

/* Return 1 if p is likely a prime after mr_depth rounds of rabin miller.
 For mr_depth == 8, this is an ironclad primality
 test for suspected primes p < 3.4 x 10^{14}, and extremely accurate
 prime assessment for any-size candidate p.
 For mr_depth = 32, the probability if a false prime
 is estimated as 2^(-64).
 Note that the result "p composite" is, however, definitive.
 TODO: this really belongs in cczp, since everything it does is in zp.
 */
int cczp_rabin_miller(cczp_t zp, unsigned long mr_depth) {
    cc_size n = cczp_n(zp);
    const cc_unit *p = cczp_prime(zp);
    cc_unit pm1[n], d[n], x[n], base[n];

#if PERFORM_IMPLICIT_SIEVE
	switch(ccn_prime_sieve(n, p)) {
		case SIEVE_PRIME:
			return 1;
		case SIEVE_COMPOSITE:
			return 0;
		case SIEVE_CANDIDATE:
			/* proceed... */
			break;
	}
#else
	/* We at least have to ensure that the number isn't a known prime
	   that we'll be using below.  */
	if (ccn_is_known_prime(n, p)) {
		return 1;
	}
#endif	/* PERFORM_IMPLICIT_SIEVE */

	if (mr_depth > ccn_prime_table_n) {
		mr_depth = ccn_prime_table_n;
	}
    ccn_sub1(n, pm1, p, 1);
    size_t s = ccn_trailing_zeros(n, pm1);
    ccn_shift_right_multi(n, d, pm1, s);

    cczp_init(zp);

	/* Now, p-1 = 2^s * d. */
	for (unsigned long j = 0; j < mr_depth; ++j) {
        ccn_seti(n, base, ccn_prime_table[j]);
        cczp_power(zp, x, base, d);
        if (!ccn_is_one(n, x)) {
            size_t r = 1;
            while (ccn_cmp(n, pm1, x) != 0) {
                if (r++ >= s)
                    return 0;

                cczp_sqr(zp, x, x);
                if (ccn_is_one(n, x))
                    return 0;
            }
        }
	}
	/* it's prime */
	return 1;
}
