name: Generate docs
on:
  push:
    branches: [ master ]
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update apt cache
      run: sudo apt-get update
    - name: install prereqs
      env: 
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get -y install plantuml doxygen
    - name: run plantuml
      working-directory: plugins_tools/eid-viewer/uml
      run: plantuml -o $(pwd) be-statemach-docs.puml
    - name: run doxygen
      working-directory: doc/sdk/eidviewer
      run: doxygen Doxyfile
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/sdk/eidviewer/html
